/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Ireport;
import Modelo.OPAlter;
import Modelo.Tienda;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;

/**
 *
 * @author Diego
 */
public class panelinformeequipos extends javax.swing.JPanel {
private Tienda Tienda;
private Ireport Ireport;
private SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form panelinformeequipos
     */
    public panelinformeequipos() {
        Tienda = new Tienda();
        Ireport = new Ireport();
        initComponents();
        
        JSpinner.DateEditor editor1= new JSpinner.DateEditor(spinnerfecha1, "dd/MM/yyyy");
        JFormattedTextField ftf1 = editor1.getTextField();
        ftf1.setEditable(false);
        spinnerfecha1.setEditor(editor1);
        
        JSpinner.DateEditor editor2= new JSpinner.DateEditor(spinnerfecha2, "dd/MM/yyyy");
        JFormattedTextField ftf2 = editor2.getTextField();
        ftf2.setEditable(false);
        spinnerfecha2.setEditor(editor2);
        combotiendas.setModel(Tienda.comboTiendas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        paneltiendas = new javax.swing.JPanel();
        lbltiendas = new javax.swing.JLabel();
        combotiendas = new javax.swing.JComboBox();
        panelfechas = new javax.swing.JPanel();
        lblfechas = new javax.swing.JLabel();
        radioestemes = new javax.swing.JRadioButton();
        radioesteaño = new javax.swing.JRadioButton();
        radioentre = new javax.swing.JRadioButton();
        lbla = new javax.swing.JLabel();
        spinnerfecha1 = new javax.swing.JSpinner();
        spinnerfecha2 = new javax.swing.JSpinner();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        paneltiendas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltiendas.setText("Seleccione Tienda Para generar Informe");

        javax.swing.GroupLayout paneltiendasLayout = new javax.swing.GroupLayout(paneltiendas);
        paneltiendas.setLayout(paneltiendasLayout);
        paneltiendasLayout.setHorizontalGroup(
            paneltiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltiendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneltiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltiendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combotiendas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneltiendasLayout.setVerticalGroup(
            paneltiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltiendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltiendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combotiendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        panelfechas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblfechas.setText("Fechas");

        buttonGroup1.add(radioestemes);
        radioestemes.setSelected(true);
        radioestemes.setText("Este Mes");
        radioestemes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioestemesItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radioesteaño);
        radioesteaño.setText("Este Año");
        radioesteaño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioesteañoItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radioentre);
        radioentre.setText("Entre");
        radioentre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioentreItemStateChanged(evt);
            }
        });

        lbla.setText("A");

        spinnerfecha1.setModel(new javax.swing.SpinnerDateModel());
        spinnerfecha1.setEnabled(false);

        spinnerfecha2.setModel(new javax.swing.SpinnerDateModel());
        spinnerfecha2.setEnabled(false);

        javax.swing.GroupLayout panelfechasLayout = new javax.swing.GroupLayout(panelfechas);
        panelfechas.setLayout(panelfechasLayout);
        panelfechasLayout.setHorizontalGroup(
            panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblfechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelfechasLayout.createSequentialGroup()
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(radioesteaño, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioestemes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelfechasLayout.createSequentialGroup()
                                .addComponent(radioentre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerfecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelfechasLayout.setVerticalGroup(
            panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfechasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfechas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioestemes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioesteaño)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioentre)
                    .addComponent(lbla)
                    .addComponent(spinnerfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerfecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneltiendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelfechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneltiendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelfechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioestemesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioestemesItemStateChanged
        if(evt.getStateChange()==1){
            spinnerfecha1.setEnabled(false);
            spinnerfecha2.setEnabled(false);
        }
    }//GEN-LAST:event_radioestemesItemStateChanged

    private void radioesteañoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioesteañoItemStateChanged
        if(evt.getStateChange()==1){
            spinnerfecha1.setEnabled(false);
            spinnerfecha2.setEnabled(false);
        }
    }//GEN-LAST:event_radioesteañoItemStateChanged

    private void radioentreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioentreItemStateChanged
        if(evt.getStateChange()==1){
            spinnerfecha1.setEnabled(true);
            spinnerfecha2.setEnabled(true);
        }
    }//GEN-LAST:event_radioentreItemStateChanged

    public void mostrarInforme(){
        String codtienda=null;
        String fechainicio=null;
        String fechatermino=null;
        if(radioestemes.isSelected()){
            fechatermino=df.format(new Date());
            fechainicio=df.format(OPAlter.restamesano(new Date(),"mes", -1));
        }
        else if(radioesteaño.isSelected()){
            fechatermino=df.format(new Date());
            fechainicio=df.format(OPAlter.restamesano(new Date(),"año", -1));
        }
        else if(radioentre.isSelected()){
            fechatermino=df.format(spinnerfecha2.getModel().getValue());
            fechainicio=df.format(spinnerfecha1.getModel().getValue());
            lblfechas.setForeground(Color.BLACK);
        }
        if(combotiendas.getSelectedIndex()==0){codtienda=null; lbltiendas.setForeground(Color.red);}
        else{codtienda=String.valueOf(((Tienda)combotiendas.getSelectedItem()).getCODTIENDA()); lbltiendas.setForeground(Color.black);}
        Ireport.informeEquipo(codtienda, fechainicio, fechatermino).setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combotiendas;
    private javax.swing.JLabel lbla;
    private javax.swing.JLabel lblfechas;
    private javax.swing.JLabel lbltiendas;
    private javax.swing.JPanel panelfechas;
    private javax.swing.JPanel paneltiendas;
    private javax.swing.JRadioButton radioentre;
    private javax.swing.JRadioButton radioesteaño;
    private javax.swing.JRadioButton radioestemes;
    private javax.swing.JSpinner spinnerfecha1;
    private javax.swing.JSpinner spinnerfecha2;
    // End of variables declaration//GEN-END:variables
}
