/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cliente;
import Modelo.Equipo;
import Modelo.Ireport;
import Modelo.OPAlter;
import Modelo.OrdenDeTrabajo;
import Modelo.Personal;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.KeyStroke;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class panelmodificarorden extends javax.swing.JPanel {
private Personal Personal = new Personal();
private Cliente Cliente = new Cliente();
private Equipo Equipo = new Equipo();
private Ireport Ireport = new Ireport();
private OrdenDeTrabajo Ordendetrabajo = new OrdenDeTrabajo();
private SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
private SpinnerDateModel spinnmodelo = new SpinnerDateModel();
private DefaultTableModel modelo;

    /**
     * Creates new form panelmodificarorden
     */
    public panelmodificarorden() {
        initComponents();
        this.txtabono.setDocument(new RestringeTextField(0,true));
        this.txtadiagnostico.setDocument(new RestringeTextField(100));
        this.txtaobservaciones.setDocument(new RestringeTextField(100));
        this.txttotal.setDocument(new RestringeTextField(0,true));
        JSpinner.DateEditor editor1= new JSpinner.DateEditor(spinnerfechaentrega, "dd/MM/yyyy");
        JFormattedTextField ftf1 = editor1.getTextField();
        ftf1.setEditable(false);
        spinnerfechaentrega.setEditor(editor1);
        modelo = (DefaultTableModel) tablerepuestos.getModel();
        tablerepuestos.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "Enter");
        tablerepuestos.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0), "Delete");
        tablerepuestos.getActionMap().put("Enter", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            switch(tablerepuestos.getSelectedColumn()){
                case 1:
                    if(tablerepuestos.getModel().getValueAt(tablerepuestos.getModel().getRowCount()-1, 1)!=null){
                        if(!String.valueOf(tablerepuestos.getModel().getValueAt(tablerepuestos.getModel().getRowCount()-1, 1)).trim().isEmpty()){
                            ((DefaultTableModel)(tablerepuestos.getModel())).addRow(new Object[]{Ordendetrabajo.getNUM_ORDEN(), "", false});
                            tablerepuestos.setRowSelectionInterval(tablerepuestos.getModel().getRowCount()-1, tablerepuestos.getModel().getRowCount()-1);
                            tablerepuestos.scrollRectToVisible(tablerepuestos.getCellRect(tablerepuestos.getRowCount()-1, 0, true));
                        }
                    }
                    break;
                case 2:
                    if(tablerepuestos.getModel().getValueAt(tablerepuestos.getSelectedRow(), 2)==true){
                        tablerepuestos.getModel().setValueAt(false, tablerepuestos.getSelectedRow(), 2);
                    }else{
                        tablerepuestos.getModel().setValueAt(true, tablerepuestos.getSelectedRow(), 2);
                    }
            }
            
        }
    });
        tablerepuestos.getActionMap().put("Delete", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent ae) {
            if(tablerepuestos.getSelectedRow()>=0){
                ((DefaultTableModel)tablerepuestos.getModel()).removeRow(tablerepuestos.getSelectedRow());
                if(tablerepuestos.getModel().getRowCount()<=0){
                    ((DefaultTableModel)tablerepuestos.getModel()).addRow(new Object[]{Ordendetrabajo.getNUM_ORDEN(),"", false});
                }
            }
        }
    });
        limpiar();
    }

    public JComboBox getComboguia() {
        return comboguia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelidentificador = new javax.swing.JPanel();
        lbltituloidentificador = new javax.swing.JLabel();
        lblcodigodeguia = new javax.swing.JLabel();
        comboguia = new javax.swing.JComboBox();
        lblimeiequipo = new javax.swing.JLabel();
        txtimei = new javax.swing.JTextField();
        lblicono = new javax.swing.JLabel();
        panelequipo = new javax.swing.JPanel();
        lbltituloequipo = new javax.swing.JLabel();
        lblmarca = new javax.swing.JLabel();
        lblmodelo = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        panelcliente = new javax.swing.JPanel();
        lbltitulocliente = new javax.swing.JLabel();
        lblrut = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        panelfechas = new javax.swing.JPanel();
        lbltitulofechas = new javax.swing.JLabel();
        lblfechaingreso = new javax.swing.JLabel();
        lblfechaentrega = new javax.swing.JLabel();
        txtfechaingreso = new javax.swing.JTextField();
        spinnerfechaentrega = new javax.swing.JSpinner();
        panelorden = new javax.swing.JPanel();
        lbltecnico = new javax.swing.JLabel();
        lblfalla = new javax.swing.JLabel();
        lblestadoorden = new javax.swing.JLabel();
        combotecnico = new javax.swing.JComboBox();
        combofalla = new javax.swing.JComboBox();
        comboestado = new javax.swing.JComboBox();
        lbldiagnostico = new javax.swing.JLabel();
        lblobservaciones = new javax.swing.JLabel();
        scrolldiagnostico = new javax.swing.JScrollPane();
        txtadiagnostico = new javax.swing.JTextArea();
        scrollobservaciones = new javax.swing.JScrollPane();
        txtaobservaciones = new javax.swing.JTextArea();
        lblabono = new javax.swing.JLabel();
        txtabono = new javax.swing.JTextField();
        lbltotal = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        scrollrepuestos = new javax.swing.JScrollPane();
        tablerepuestos = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        panelidentificador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltituloidentificador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltituloidentificador.setText("Ingrese un identificador para acceder a la Orden");

        lblcodigodeguia.setText("Codigo de Orden");

        comboguia.setEditable(true);
        comboguia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboguiaItemStateChanged(evt);
            }
        });
        comboguia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboguiaFocusLost(evt);
            }
        });

        lblimeiequipo.setText("Imei Equipo");

        txtimei.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtimeiFocusLost(evt);
            }
        });

        lblicono.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\PROYECTO TRABAJO DE TITULO\\InventarioServicioTecnico\\src\\Vista\\icon\\codigo-de-barras-escaneado-icono--psd_30-2603.png")); // NOI18N

        javax.swing.GroupLayout panelidentificadorLayout = new javax.swing.GroupLayout(panelidentificador);
        panelidentificador.setLayout(panelidentificadorLayout);
        panelidentificadorLayout.setHorizontalGroup(
            panelidentificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelidentificadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelidentificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelidentificadorLayout.createSequentialGroup()
                        .addGroup(panelidentificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblimeiequipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtimei, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelidentificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcodigodeguia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboguia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbltituloidentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblicono, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelidentificadorLayout.setVerticalGroup(
            panelidentificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelidentificadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelidentificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelidentificadorLayout.createSequentialGroup()
                        .addComponent(lbltituloidentificador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelidentificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcodigodeguia)
                            .addComponent(lblimeiequipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelidentificadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboguia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtimei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblicono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelequipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltituloequipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltituloequipo.setText("Datos del Equipo Telefonico");

        lblmarca.setText("Marca (Fabricante)");

        lblmodelo.setText("Modelo");

        txtmarca.setEditable(false);

        txtmodelo.setEditable(false);

        javax.swing.GroupLayout panelequipoLayout = new javax.swing.GroupLayout(panelequipo);
        panelequipo.setLayout(panelequipoLayout);
        panelequipoLayout.setHorizontalGroup(
            panelequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelequipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltituloequipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelequipoLayout.createSequentialGroup()
                        .addGroup(panelequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblmarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmodelo)
                            .addComponent(lblmodelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelequipoLayout.setVerticalGroup(
            panelequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelequipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltituloequipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmarca)
                    .addComponent(lblmodelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltitulocliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltitulocliente.setText("Datos Cliente");

        lblrut.setText("Rut");

        lbltelefono.setText("Telefono");

        lblnombre.setText("Nombre");

        lblcorreo.setText("Correo");

        txtrut.setEditable(false);

        txttelefono.setEditable(false);

        txtnombre.setEditable(false);

        txtcorreo.setEditable(false);

        javax.swing.GroupLayout panelclienteLayout = new javax.swing.GroupLayout(panelcliente);
        panelcliente.setLayout(panelclienteLayout);
        panelclienteLayout.setHorizontalGroup(
            panelclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitulocliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelclienteLayout.createSequentialGroup()
                        .addGroup(panelclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblrut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbltelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcorreo)
                            .addComponent(lblcorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelclienteLayout.setVerticalGroup(
            panelclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulocliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrut)
                    .addComponent(lbltelefono)
                    .addComponent(lblnombre)
                    .addComponent(lblcorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelfechas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltitulofechas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltitulofechas.setText("Fechas Orden de Trabajo");

        lblfechaingreso.setText("Fecha Ingreso");

        lblfechaentrega.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblfechaentrega.setText("Fecha Entrega");

        txtfechaingreso.setEditable(false);

        spinnerfechaentrega.setModel(new javax.swing.SpinnerDateModel());
        spinnerfechaentrega.setEnabled(false);
        spinnerfechaentrega.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerfechaentregaStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelfechasLayout = new javax.swing.GroupLayout(panelfechas);
        panelfechas.setLayout(panelfechasLayout);
        panelfechasLayout.setHorizontalGroup(
            panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitulofechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelfechasLayout.createSequentialGroup()
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfechaingreso, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblfechaentrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerfechaentrega, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelfechasLayout.setVerticalGroup(
            panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfechasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulofechas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfechaingreso)
                    .addComponent(lblfechaentrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerfechaentrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelorden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltecnico.setText("Tecnico");

        lblfalla.setText("Motivo (Falla)");

        lblestadoorden.setText("Estado de la Orden");

        combotecnico.setEnabled(false);

        combofalla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una Causa", "Quiebre Pantalla", "Cambio/Reparacion de Flex", "Cambio/Reparacion Placas", "Cambio Auricular Microfono", "Limpieza / Zulfurado / etc.", "Desbloqueo", "Otros" }));
        combofalla.setEnabled(false);

        comboestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Estado", "Ingresado", "Procesando", "Terminado" }));
        comboestado.setEnabled(false);

        lbldiagnostico.setText("Diagnostico");

        lblobservaciones.setText("Observaciones");

        txtadiagnostico.setEditable(false);
        txtadiagnostico.setColumns(20);
        txtadiagnostico.setLineWrap(true);
        txtadiagnostico.setRows(5);
        txtadiagnostico.setWrapStyleWord(true);
        scrolldiagnostico.setViewportView(txtadiagnostico);

        txtaobservaciones.setEditable(false);
        txtaobservaciones.setColumns(20);
        txtaobservaciones.setLineWrap(true);
        txtaobservaciones.setRows(5);
        txtaobservaciones.setWrapStyleWord(true);
        scrollobservaciones.setViewportView(txtaobservaciones);

        lblabono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblabono.setText("Abono");

        txtabono.setEditable(false);

        lbltotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltotal.setText("Total");

        txttotal.setEditable(false);

        tablerepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Num Orden", "Repuesto", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablerepuestos.getTableHeader().setResizingAllowed(false);
        tablerepuestos.getTableHeader().setReorderingAllowed(false);
        scrollrepuestos.setViewportView(tablerepuestos);
        tablerepuestos.getColumnModel().getColumn(0).setMinWidth(0);
        tablerepuestos.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablerepuestos.getColumnModel().getColumn(0).setMaxWidth(0);
        tablerepuestos.getColumnModel().getColumn(1).setResizable(false);
        tablerepuestos.getColumnModel().getColumn(2).setMaxWidth(90);

        javax.swing.GroupLayout panelordenLayout = new javax.swing.GroupLayout(panelorden);
        panelorden.setLayout(panelordenLayout);
        panelordenLayout.setHorizontalGroup(
            panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelordenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrolldiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lbldiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combotecnico, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblfalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combofalla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblobservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollobservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelordenLayout.createSequentialGroup()
                        .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboestado, javax.swing.GroupLayout.Alignment.LEADING, 0, 143, Short.MAX_VALUE)
                            .addComponent(lblestadoorden, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblabono, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtabono, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(txttotal, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)))
                    .addComponent(scrollrepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelordenLayout.setVerticalGroup(
            panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelordenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltecnico)
                    .addComponent(lblfalla)
                    .addComponent(lblestadoorden)
                    .addComponent(lblabono)
                    .addComponent(txtabono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combotecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combofalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbltotal)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelordenLayout.createSequentialGroup()
                        .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldiagnostico)
                            .addComponent(lblobservaciones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrolldiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(scrollobservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(scrollrepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelidentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelfechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelequipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelidentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelfechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtimeiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtimeiFocusLost
        if(OPAlter.validaimei(txtimei.getText())){
            lblimeiequipo.setForeground(Color.BLACK);
            Ordendetrabajo.setIMEI(txtimei.getText().substring(0, 8));
            Ordendetrabajo.setSERIE(txtimei.getText().substring(8,txtimei.getText().length()));
            comboguia.setModel(Ordendetrabajo.buscarOrdenesImei());
        }else{
            limpiar();
            lblimeiequipo.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtimeiFocusLost

    private void comboguiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboguiaItemStateChanged
        buscaordenaccion();
    }//GEN-LAST:event_comboguiaItemStateChanged

    private void comboguiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboguiaFocusLost
        buscaordenaccion();
    }//GEN-LAST:event_comboguiaFocusLost

    private void spinnerfechaentregaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerfechaentregaStateChanged
        SimpleDateFormat dfd = new SimpleDateFormat("EEEE");
        switch (dfd.format(spinnerfechaentrega.getModel().getValue())) {
        case "domingo":
            lblfechaentrega.setForeground(Color.ORANGE);
            break;
        case "sábado":
            lblfechaentrega.setForeground(Color.yellow);
            break;
        default:
            lblfechaentrega.setForeground(Color.BLACK);
            break;
    }
    }//GEN-LAST:event_spinnerfechaentregaStateChanged

    public final void limpiar(){
               combotecnico.setModel(Personal.comboTecnicosMiTienda(23));
               this.txtabono.setText("");
               this.txtadiagnostico.setText("");
               this.txtaobservaciones.setText("");
               this.txtcorreo.setText("");
               this.txtfechaingreso.setText("");
               this.txtmarca.setText("");
               this.txtmodelo.setText("");
               this.txtnombre.setText("");
               this.txtrut.setText("");
               this.txttelefono.setText("");
               this.txttotal.setText("");
               this.lblestadoorden.setText("Estado de la Orden");
               this.lblfalla.setText("Motivo (Falla)");
               this.lbltecnico.setText("Tecnico");
               combofalla.setSelectedIndex(0);
               comboestado.setSelectedIndex(0);
               tablerepuestos.setEnabled(false);
               modelo.setRowCount(0);
               spinnmodelo.setStart(null);
               spinnmodelo.setValue(new Date());
               spinnerfechaentrega.setModel(spinnmodelo);
               txtabono.setEditable(false);
               txtadiagnostico.setEditable(false);
               txtaobservaciones.setEditable(false);
               txttotal.setEditable(false);
               txtimei.setText("");
               lblimeiequipo.setForeground(Color.BLACK);
               lblcodigodeguia.setForeground(Color.BLACK);
               this.spinnerfechaentrega.setEnabled(false);
               this.comboestado.setEnabled(false);
               this.combofalla.setEnabled(false);
               this.combotecnico.setEnabled(false);
               this.comboguia.setModel(new javax.swing.DefaultComboBoxModel(new String[] {""}));
               SimpleDateFormat dfd = new SimpleDateFormat("EEEE");
                switch (dfd.format(spinnerfechaentrega.getModel().getValue())) {
                case "domingo":
                    lblfechaentrega.setForeground(Color.ORANGE);
                    break;
                case "sábado":
                    lblfechaentrega.setForeground(Color.yellow);
                    break;
                default:
                    lblfechaentrega.setForeground(Color.BLACK);
                    break;
                }
    }

    public void modificar(){
        try{
            Ordendetrabajo.setNUM_ORDEN(Integer.parseInt(String.valueOf(comboguia.getSelectedItem()).substring(6, String.valueOf(comboguia.getSelectedItem()).length())));
            Ordendetrabajo.setIMEI(String.valueOf(comboguia.getSelectedItem()));
            if(Integer.parseInt(txtabono.getText())<=Integer.parseInt(txttotal.getText())){
                Ordendetrabajo.setABONO(Integer.parseInt(txtabono.getText()));
                Ordendetrabajo.setTOTAL(Integer.parseInt(txttotal.getText()));
                lblabono.setForeground(Color.BLACK);
                lbltotal.setForeground(Color.BLACK);
                lbltotal.setText("Total");
                lblabono.setText("Abono");
            }else{
                Ordendetrabajo.setABONO(null);
                Ordendetrabajo.setTOTAL(null);
                lblabono.setForeground(Color.red);
                lbltotal.setForeground(Color.red);
                lbltotal.setText("Total >");
                lblabono.setText("Abono <");
            }
            Ordendetrabajo.setDIAGNO(txtadiagnostico.getText());
            Ordendetrabajo.setDESCRIP_OBSER(txtaobservaciones.getText());
            if(comboestado.getSelectedIndex()!=0){Ordendetrabajo.setESTADO(String.valueOf(comboestado.getSelectedItem()));}
            if(combofalla.getSelectedIndex()!=0){Ordendetrabajo.setFALLA(String.valueOf(combofalla.getSelectedItem()));}
            Ordendetrabajo.setFECHA_EN(spinnmodelo.getDate());
            if(combotecnico.getSelectedIndex()!=0){Ordendetrabajo.setRUT_P(String.valueOf(Personal.getListmodelrut().getElementAt(combotecnico.getSelectedIndex())));}
            if(Ordendetrabajo.modificarOrdenA()){
                for(int i=0;i<modelo.getRowCount();i++){
                    Ordendetrabajo.EliminaRepuesto((Integer)modelo.getValueAt(i, 0));
                }
                Ordendetrabajo.IngresaRepuesto(modelo);
                JOptionPane.showMessageDialog(null, "(ORDEN) Cambios realizados con Exito"); limpiar();}
            else{JOptionPane.showMessageDialog(null, "(ORDEN) Uno de los datos Ingresados es incorrecto");}
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "(ORDEN) Uno de los datos Ingresados es incorrecto");
        }
    }

    public void eliminar(){
        try{
           Ordendetrabajo.setNUM_ORDEN(Integer.parseInt(String.valueOf(comboguia.getSelectedItem()).substring(6, String.valueOf(comboguia.getSelectedItem()).length())));
           Ordendetrabajo.setIMEI(String.valueOf(comboguia.getSelectedItem()));
           if(Ordendetrabajo.eliminarOrden()){
               Ordendetrabajo.EliminaRepuesto(Ordendetrabajo.getNUM_ORDEN());
               JOptionPane.showMessageDialog(null, "(ORDEN) La Orden se ha eliminado con exito")
               ;limpiar();}
           else{JOptionPane.showMessageDialog(null, "(ORDEN) No se pudo Eliminar debido a un error en el codigo ingresado");}
        }catch(Exception e){JOptionPane.showMessageDialog(null, "(ORDEN) No se pudo Eliminar debido a un error en el codigo ingresado");}
    }

    public void ver(){
        try{
           Ordendetrabajo.setNUM_ORDEN(Integer.parseInt(String.valueOf(comboguia.getSelectedItem()).substring(6, String.valueOf(comboguia.getSelectedItem()).length())));
           Ordendetrabajo.setIMEI(String.valueOf(comboguia.getSelectedItem()));
           if(Ordendetrabajo.buscarOrden()){Ireport.verOrden(Ordendetrabajo.getNUM_ORDEN()).setVisible(true);}
           else{JOptionPane.showMessageDialog(null, "(ORDEN) La Orden no ha sido encontrada en la base de datos");}
        }catch(Exception e){JOptionPane.showMessageDialog(null, "(ORDEN) Uno de los datos Ingresados es incorrecto");}
    }

    private void buscaordenaccion(){
        try{
           Ordendetrabajo.setNUM_ORDEN(Integer.parseInt(String.valueOf(comboguia.getSelectedItem()).substring(6, String.valueOf(comboguia.getSelectedItem()).length())));
           Ordendetrabajo.setIMEI(String.valueOf(comboguia.getSelectedItem()));
           if(Ordendetrabajo.buscarOrden()){
               Personal.setMRUT_P(Ordendetrabajo.getRUT_P());
               Cliente.setRUT_C(Ordendetrabajo.getRUT_C());
               Equipo.setIMEI(Ordendetrabajo.getIMEI());
               Personal.buscarPersonal();
               Cliente.buscarCliente();
               Equipo.buscarImei();
               lblcodigodeguia.setForeground(Color.BLACK);
               this.txtabono.setText(String.valueOf(Ordendetrabajo.getABONO()));
               this.txtadiagnostico.setText(Ordendetrabajo.getDIAGNO());
               this.txtaobservaciones.setText(Ordendetrabajo.getDESCRIP_OBSER());
               this.txtcorreo.setText(Cliente.getEMAIL());
               this.txtfechaingreso.setText(df.format(Ordendetrabajo.getFECHA_ING()));
               this.txtmarca.setText(Equipo.getMARCA());
               this.txtmodelo.setText(Equipo.getMODELO());
               this.txtnombre.setText(Cliente.getNOMBRE_C());
               this.txtrut.setText(Ordendetrabajo.getRUT_C());
               this.txttelefono.setText(String.valueOf(Cliente.getTELEFONO()));
               this.txttotal.setText(String.valueOf(Ordendetrabajo.getTOTAL()));
               if(Personal.getMNOMBRE_P().length()>=15){this.lbltecnico.setText("Tecnico Actual ("+Personal.getMNOMBRE_P().substring(0, 15)+")");}
               else{this.lbltecnico.setText("Tecnico Actual ("+Personal.getMNOMBRE_P()+")");}
               this.lblestadoorden.setText("Estado de la Orden ("+Ordendetrabajo.getESTADO()+")");
               this.lblfalla.setText("Motivo ("+Ordendetrabajo.getFALLA()+")");
               spinnmodelo.setStart(df.parse(df.format(Ordendetrabajo.getFECHA_ING())));
               spinnmodelo.setValue(Ordendetrabajo.getFECHA_EN());
               spinnerfechaentrega.setModel(spinnmodelo);
               txtadiagnostico.setEditable(true);
               txtaobservaciones.setEditable(true);
               this.spinnerfechaentrega.setEnabled(true);
               this.comboestado.setEnabled(true);
               this.combofalla.setEnabled(true);
               if("A".equals(Personal.getPERMISO())){
               txtabono.setEditable(true);
               txttotal.setEditable(true);
               this.combotecnico.setEnabled(true);}
               SimpleDateFormat dfd = new SimpleDateFormat("EEEE");
                switch (dfd.format(spinnerfechaentrega.getModel().getValue())) {
                case "domingo":
                    lblfechaentrega.setForeground(Color.ORANGE);
                    break;
                case "sábado":
                    lblfechaentrega.setForeground(Color.yellow);
                    break;
                default:
                    lblfechaentrega.setForeground(Color.BLACK);
                    break;
                }
               if(Ordendetrabajo.tablaRepuestos(modelo, Ordendetrabajo.getNUM_ORDEN()).getRowCount()>=1){
                   modelo = Ordendetrabajo.tablaRepuestos(modelo, Ordendetrabajo.getNUM_ORDEN());
               }else{
                   modelo.setRowCount(0);
                   modelo.addRow(new Object[]{Ordendetrabajo.getNUM_ORDEN(),"", false});
               }
               tablerepuestos.setEnabled(true);
           }else{
                JOptionPane.showMessageDialog(null, "(ORDEN) La Orden no ha sido encontrada en la base de datos");
            }
        }catch(Exception e){
            lblcodigodeguia.setForeground(Color.red);
            limpiar();
        }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboestado;
    private javax.swing.JComboBox combofalla;
    private javax.swing.JComboBox comboguia;
    private javax.swing.JComboBox combotecnico;
    private javax.swing.JLabel lblabono;
    private javax.swing.JLabel lblcodigodeguia;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbldiagnostico;
    private javax.swing.JLabel lblestadoorden;
    private javax.swing.JLabel lblfalla;
    private javax.swing.JLabel lblfechaentrega;
    private javax.swing.JLabel lblfechaingreso;
    private javax.swing.JLabel lblicono;
    private javax.swing.JLabel lblimeiequipo;
    private javax.swing.JLabel lblmarca;
    private javax.swing.JLabel lblmodelo;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblobservaciones;
    private javax.swing.JLabel lblrut;
    private javax.swing.JLabel lbltecnico;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JLabel lbltitulocliente;
    private javax.swing.JLabel lbltituloequipo;
    private javax.swing.JLabel lbltitulofechas;
    private javax.swing.JLabel lbltituloidentificador;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JPanel panelcliente;
    private javax.swing.JPanel panelequipo;
    private javax.swing.JPanel panelfechas;
    private javax.swing.JPanel panelidentificador;
    private javax.swing.JPanel panelorden;
    private javax.swing.JScrollPane scrolldiagnostico;
    private javax.swing.JScrollPane scrollobservaciones;
    private javax.swing.JScrollPane scrollrepuestos;
    private javax.swing.JSpinner spinnerfechaentrega;
    private javax.swing.JTable tablerepuestos;
    private javax.swing.JTextField txtabono;
    private javax.swing.JTextArea txtadiagnostico;
    private javax.swing.JTextArea txtaobservaciones;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtfechaingreso;
    private javax.swing.JTextField txtimei;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtrut;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
