/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cliente;
import Modelo.Equipo;
import Modelo.Ireport;
import Modelo.OPAlter;
import Modelo.OrdenDeTrabajo;
import Modelo.Personal;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Diego
 */
public class panelagregaorden extends javax.swing.JPanel {
private Cliente Cliente = new Cliente();
private Equipo Equipo = new Equipo();
private Personal Personal = new Personal();
private OrdenDeTrabajo Ordendetrabajo = new OrdenDeTrabajo();
private Ireport Ireport = new Ireport();
private boolean verifica1 = false, verifica2=false;
private SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
private SpinnerDateModel spinnmodelo = new SpinnerDateModel();
    /**
     * Creates new form panelagregaorden
     */
    public panelagregaorden() {
        initComponents();
        txtcorreo.setDocument(new RestringeTextField(60));
        txtdireccion.setDocument(new RestringeTextField(60));
        txtnombre.setDocument(new RestringeTextField(60));
        txttelefono.setDocument(new RestringeTextField(9,true));
        txtimei.setDocument(new RestringeTextField(15,true));
        txtmarca.setDocument(new RestringeTextField(50));
        txtmodelo.setDocument(new RestringeTextField(60));
        txtaobservaciones.setDocument(new RestringeTextField(100));
        txtadiagnostico.setDocument(new RestringeTextField(100));
        txtabono.setDocument(new RestringeTextField(9,true));
        txttotal.setDocument(new RestringeTextField(9,true));
        JSpinner.DateEditor editor1= new JSpinner.DateEditor(spinnerfechaentrega, "dd/MM/yyyy");
        JFormattedTextField ftf1 = editor1.getTextField();
        ftf1.setEditable(false);
        spinnerfechaentrega.setEditor(editor1);
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelagregacliente = new javax.swing.JPanel();
        lbltitulocliente = new javax.swing.JLabel();
        lblrut = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        txtdv = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lbltelefono = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        lbldireccion = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        lblcorreo = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        panelagregaequipo = new javax.swing.JPanel();
        lbltituloequipo = new javax.swing.JLabel();
        lblimei = new javax.swing.JLabel();
        txtimei = new javax.swing.JTextField();
        lblmarca = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        lblmodelo = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        panelagregaorden1 = new javax.swing.JPanel();
        lbltituloorden = new javax.swing.JLabel();
        lblfechaingreso = new javax.swing.JLabel();
        lblfechaentrega = new javax.swing.JLabel();
        txtfechaingreso = new javax.swing.JTextField();
        spinnerfechaentrega = new javax.swing.JSpinner();
        lbltecnico = new javax.swing.JLabel();
        combotecnico = new javax.swing.JComboBox();
        lblfalla = new javax.swing.JLabel();
        combofalla = new javax.swing.JComboBox();
        lbldiagnostico = new javax.swing.JLabel();
        scrolldiagnostico = new javax.swing.JScrollPane();
        txtadiagnostico = new javax.swing.JTextArea();
        lblobservaciones = new javax.swing.JLabel();
        scrollobservaciones = new javax.swing.JScrollPane();
        txtaobservaciones = new javax.swing.JTextArea();
        lblabono = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        txtabono = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelagregacliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltitulocliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltitulocliente.setText("Datos Cliente");

        lblrut.setText("Rut:");

        txtrut.setEditable(false);
        txtrut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtrutFocusGained(evt);
            }
        });

        txtdv.setEditable(false);
        txtdv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdvFocusLost(evt);
            }
        });
        txtdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdvKeyPressed(evt);
            }
        });

        lblnombre.setText("Nombre:");

        txtnombre.setEditable(false);

        lbltelefono.setText("Telefono:");

        txttelefono.setEditable(false);

        lbldireccion.setText("Direccion:");

        txtdireccion.setEditable(false);

        lblcorreo.setText("Correo Electronico:");

        txtcorreo.setEditable(false);

        javax.swing.GroupLayout panelagregaclienteLayout = new javax.swing.GroupLayout(panelagregacliente);
        panelagregacliente.setLayout(panelagregaclienteLayout);
        panelagregaclienteLayout.setHorizontalGroup(
            panelagregaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelagregaclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelagregaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltitulocliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblrut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnombre)
                    .addComponent(lbltelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttelefono)
                    .addComponent(lbldireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdireccion)
                    .addComponent(lblcorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelagregaclienteLayout.createSequentialGroup()
                        .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addComponent(txtcorreo))
                .addContainerGap())
        );
        panelagregaclienteLayout.setVerticalGroup(
            panelagregaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelagregaclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulocliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelagregaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbltelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblcorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        add(panelagregacliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 446));

        panelagregaequipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltituloequipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltituloequipo.setText("Datos Equipo");

        lblimei.setText("Imei:");

        txtimei.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtimeiFocusLost(evt);
            }
        });

        lblmarca.setText("Marca (Fabricante):");

        txtmarca.setEditable(false);
        txtmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmarcaKeyReleased(evt);
            }
        });

        lblmodelo.setText("Modelo");

        txtmodelo.setEditable(false);
        txtmodelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmodeloFocusGained(evt);
            }
        });
        txtmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmodeloKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelagregaequipoLayout = new javax.swing.GroupLayout(panelagregaequipo);
        panelagregaequipo.setLayout(panelagregaequipoLayout);
        panelagregaequipoLayout.setHorizontalGroup(
            panelagregaequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelagregaequipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelagregaequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltituloequipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblimei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtimei)
                    .addComponent(lblmarca, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(txtmarca)
                    .addComponent(lblmodelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtmodelo))
                .addContainerGap())
        );
        panelagregaequipoLayout.setVerticalGroup(
            panelagregaequipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelagregaequipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltituloequipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblimei)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtimei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblmarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblmodelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        add(panelagregaequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 11, -1, 446));

        panelagregaorden1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelagregaorden1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltituloorden.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltituloorden.setText("Datos Orden");
        panelagregaorden1.add(lbltituloorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 222, -1));

        lblfechaingreso.setText("Fecha Ingreso:");
        panelagregaorden1.add(lblfechaingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 32, 106, -1));

        lblfechaentrega.setText("Fecha Entrega:");
        panelagregaorden1.add(lblfechaentrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 32, 106, -1));

        txtfechaingreso.setEditable(false);
        panelagregaorden1.add(txtfechaingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 52, 106, -1));

        spinnerfechaentrega.setModel(new javax.swing.SpinnerDateModel());
        spinnerfechaentrega.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerfechaentregaStateChanged(evt);
            }
        });
        panelagregaorden1.add(spinnerfechaentrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 52, 106, -1));

        lbltecnico.setText("Tecnico:");
        panelagregaorden1.add(lbltecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 83, 222, -1));

        combotecnico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combotecnicoItemStateChanged(evt);
            }
        });
        panelagregaorden1.add(combotecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 103, 222, -1));

        lblfalla.setText("Motivo (Falla):");
        panelagregaorden1.add(lblfalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 134, 222, -1));

        combofalla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una Causa", "Quiebre Pantalla", "Cambio/Reparacion de Flex", "Cambio/Reparacion Placas", "Cambio Auricular Microfono", "Limpieza / Zulfurado / etc.", "Desbloqueo", "Otros" }));
        panelagregaorden1.add(combofalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 154, 222, -1));

        lbldiagnostico.setText("Diagnostico:");
        panelagregaorden1.add(lbldiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 185, 222, -1));

        scrolldiagnostico.setPreferredSize(new java.awt.Dimension(222, 70));

        txtadiagnostico.setColumns(20);
        txtadiagnostico.setLineWrap(true);
        txtadiagnostico.setRows(5);
        txtadiagnostico.setWrapStyleWord(true);
        scrolldiagnostico.setViewportView(txtadiagnostico);

        panelagregaorden1.add(scrolldiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 205, -1, -1));

        lblobservaciones.setText("Observaciones:");
        panelagregaorden1.add(lblobservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 286, 222, -1));

        scrollobservaciones.setPreferredSize(new java.awt.Dimension(222, 70));

        txtaobservaciones.setColumns(20);
        txtaobservaciones.setLineWrap(true);
        txtaobservaciones.setRows(5);
        txtaobservaciones.setWrapStyleWord(true);
        scrollobservaciones.setViewportView(txtaobservaciones);

        panelagregaorden1.add(scrollobservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 306, -1, -1));

        lblabono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblabono.setText("Abono:");
        panelagregaorden1.add(lblabono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 106, -1));

        lbltotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltotal.setText("Total (referencial):");
        panelagregaorden1.add(lbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        txtabono.setText("0");
        panelagregaorden1.add(txtabono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 106, -1));

        txttotal.setText("0");
        panelagregaorden1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 106, -1));

        add(panelagregaorden1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 11, 244, 446));
    }// </editor-fold>//GEN-END:initComponents

    private void txtdvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdvFocusLost
        if (OPAlter.validarut(txtrut.getText(), txtdv.getText())) {
            Cliente.setRUT_C(txtrut.getText()+"-"+txtdv.getText());
            Ordendetrabajo.setRUT_C(txtrut.getText()+"-"+txtdv.getText());
            if (Cliente.buscarCliente()) {
                lblrut.setText("Rut Cliente (Existente)");lblrut.setForeground(Color.BLACK);
                txtnombre.setText(Cliente.getNOMBRE_C()); txtnombre.setEditable(false);
                txttelefono.setText(String.valueOf(Cliente.getTELEFONO())); txttelefono.setEditable(false);
                txtdireccion.setText(Cliente.getDIRECCION()); txtdireccion.setEditable(false);
                txtcorreo.setText(Cliente.getEMAIL()); txtcorreo.setEditable(false);
                verifica1=false;
            } else {
                lblrut.setText("Rut Cliente (Nuevo)");lblrut.setForeground(Color.GREEN.darker().darker());
                txtnombre.setText(""); txtnombre.setEditable(true);
                txttelefono.setText(""); txttelefono.setEditable(true);
                txtdireccion.setText(""); txtdireccion.setEditable(true);
                txtcorreo.setText(""); txtcorreo.setEditable(true);
                verifica1=true;
            }
        }else{lblrut.setText("Rut Cliente (Invalido)");
            Cliente.setRUT_C(null);
            Ordendetrabajo.setRUT_C(null);
            lblrut.setForeground(Color.red);
            txtnombre.setText(""); txtnombre.setEditable(false);
            txttelefono.setText(""); txttelefono.setEditable(false);
            txtdireccion.setText(""); txtdireccion.setEditable(false);
            txtcorreo.setText(""); txtcorreo.setEditable(false);
            verifica1=true;
        }
    }//GEN-LAST:event_txtdvFocusLost

    private void txtrutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrutFocusGained
        txtdv.requestFocus(true);
    }//GEN-LAST:event_txtrutFocusGained

    private void txtdvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdvKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_BACK_SPACE)
        {
            try{
                txtdv.setText(String.valueOf(txtrut.getText().charAt(txtrut.getText().length()-1)));
                txtrut.setText(txtrut.getText().substring(0,txtrut.getText().length()-1));
            }catch(Exception e){txtdv.setText("");}
        }
        else if(OPAlter.esNumerico(String.valueOf(evt.getKeyChar())) || evt.getKeyChar()=='k'||evt.getKeyChar()=='K')
        {
            if(!txtdv.getText().isEmpty() && OPAlter.esNumerico(txtdv.getText())&& txtrut.getText().length()<=7)
            {
                txtrut.setText(txtrut.getText()+txtdv.getText());
            }
            if (String.valueOf(evt.getKeyChar()).matches("[0-9]") || evt.getKeyChar()=='k' || evt.getKeyChar()=='K')
            {
                txtdv.setText(String.valueOf(evt.getKeyChar()));
            }
        }
    }//GEN-LAST:event_txtdvKeyPressed

    private void txtimeiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtimeiFocusLost
        if(OPAlter.validaimei(txtimei.getText())){
            Equipo.setIMEI(txtimei.getText().substring(0, 8));
            Ordendetrabajo.setIMEI(txtimei.getText().substring(0, 8));
            Ordendetrabajo.setSERIE(txtimei.getText().substring(8, txtimei.getText().length()));
            if(Equipo.buscarImei()){
            lblimei.setText("Imei (Existente)");
            lblimei.setForeground(Color.black);
            txtmarca.setText(Equipo.getMARCA());
            txtmodelo.setText(Equipo.getMODELO());
            txtmarca.setEditable(false);
            txtmodelo.setEditable(false);
            verifica2=false;
            }
            else{
            lblimei.setText("Imei (Nuevo)");
            lblimei.setForeground(Color.green.darker().darker());
            txtmarca.setText("");
            txtmodelo.setText("");
            txtmarca.setEditable(true);
            txtmodelo.setEditable(true);
            verifica2=true;
            }
        }
        else{
            Equipo.setIMEI(null);
            Ordendetrabajo.setIMEI(null);
            Ordendetrabajo.setSERIE(null);
            lblimei.setText("Imei (Invalido)");
            lblimei.setForeground(Color.red);
            txtmarca.setText("");
            txtmodelo.setText("");
            txtmarca.setEditable(false);
            txtmodelo.setEditable(false);
            verifica2=true;
        }
    }//GEN-LAST:event_txtimeiFocusLost

    private void txtmarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmarcaKeyReleased
        if(txtmarca.isEditable()){
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_DELETE:
                break;
            default:
                Equipo.setMARCA(txtmarca.getText().substring(0, txtmarca.getSelectionStart()));
                txtmarca.setText(Equipo.getMARCA()+Equipo.buscarMarca());
                txtmarca.select(Equipo.getMARCA().length(), txtmarca.getText().length());
                break;
        }
        }
    }//GEN-LAST:event_txtmarcaKeyReleased

    private void txtmodeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmodeloKeyReleased
        if(txtmodelo.isEditable()){
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_DELETE:
                break;
            default:
                Equipo.setMODELO(txtmodelo.getText().substring(0, txtmodelo.getSelectionStart()));
                txtmodelo.setText(Equipo.getMODELO()+Equipo.buscarModelo());
                txtmodelo.select(Equipo.getMODELO().length(), txtmodelo.getText().length());
                break;
        }
        }
    }//GEN-LAST:event_txtmodeloKeyReleased

    private void txtmodeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmodeloFocusGained
        Equipo.setMARCA(txtmarca.getText());
    }//GEN-LAST:event_txtmodeloFocusGained

    private void combotecnicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combotecnicoItemStateChanged
        if(combotecnico.getSelectedIndex()!=0){
            Ordendetrabajo.setRUT_P(String.valueOf(Personal.getListmodelrut().getElementAt(combotecnico.getSelectedIndex())));
            lbltecnico.setForeground(Color.BLACK);
            lbltecnico.setText("Tecnico: Ordenes activas("+String.valueOf(Personal.getListmodelcantidad().getElementAt(combotecnico.getSelectedIndex()))+")" );
        }else{
            Ordendetrabajo.setRUT_P(null);
        }
    }//GEN-LAST:event_combotecnicoItemStateChanged

    private void spinnerfechaentregaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerfechaentregaStateChanged
        SimpleDateFormat dfd = new SimpleDateFormat("EEEE");
        switch (dfd.format(spinnerfechaentrega.getModel().getValue())) {
        case "domingo":
            lblfechaentrega.setForeground(Color.ORANGE);
            break;
        case "sábado":
            lblfechaentrega.setForeground(Color.yellow);
            break;
        default:
            lblfechaentrega.setForeground(Color.BLACK);
            break;
    }
    }//GEN-LAST:event_spinnerfechaentregaStateChanged

    public final void limpiar(){
        Cliente = new Cliente();
        txtrut.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        txtrut.setText("");
        txtdv.setText("");
        txtnombre.setText(""); txtnombre.setEditable(false);
        txttelefono.setText(""); txttelefono.setEditable(false);
        txtdireccion.setText(""); txtdireccion.setEditable(false);
        txtcorreo.setText(""); txtcorreo.setEditable(false);
        lblrut.setText("Rut:");
        lblrut.setForeground(Color.BLACK);
        lbltelefono.setForeground(Color.BLACK);
        
        Equipo = new Equipo();
        txtimei.setText("");
        txtmarca.setText("");
        txtmarca.setEditable(false);
        txtmodelo.setText("");
        txtmodelo.setEditable(false);
        lblimei.setText("Imei:");
        lblimei.setForeground(Color.BLACK);
        
        Ordendetrabajo = new OrdenDeTrabajo();
        lblabono.setForeground(Color.BLACK);
        lbltotal.setForeground(Color.BLACK);
        lblabono.setText("Abono");
        lbltelefono.setForeground(Color.BLACK);
        combofalla.setSelectedIndex(0);
        combotecnico.setModel(Personal.comboTecnicosMiTienda(23));
        txtaobservaciones.setText("");
        txtadiagnostico.setText("");
        txtabono.setText("0");
        txttotal.setText("0");
        lbltecnico.setText("Tecnico:");
        txtfechaingreso.setText(df.format(new Date()));
        try {spinnmodelo.setStart(df.parse(df.format(new Date())));} catch (ParseException ex) {}
        spinnmodelo.setValue(new Date());
        spinnerfechaentrega.setModel(spinnmodelo);
        SimpleDateFormat dfd = new SimpleDateFormat("EEEE");
        switch (dfd.format(spinnerfechaentrega.getModel().getValue())) {
        case "domingo":
            lblfechaentrega.setForeground(Color.ORANGE);
            break;
        case "sábado":
            lblfechaentrega.setForeground(Color.yellow);
            break;
        default:
            lblfechaentrega.setForeground(Color.BLACK);
            break;
    }
    }
    
    public void agregar(){
        lblabono.setForeground(Color.BLACK);
        lbltotal.setForeground(Color.BLACK);
        lblabono.setText("Abono");
        lbltelefono.setForeground(Color.BLACK);
        if(OPAlter.esNumerico(txttelefono.getText())){Cliente.setTELEFONO(Integer.parseInt(this.txttelefono.getText()));}
        else{
            Cliente.setTELEFONO(null); lbltelefono.setForeground(Color.BLACK);}
        Cliente.setDIRECCION(this.txtdireccion.getText());
        Cliente.setEMAIL(this.txtcorreo.getText());
        Cliente.setNOMBRE_C(this.txtnombre.getText());
        if(verifica1){Cliente.crearCliente();}
        
        Equipo.setMARCA(this.txtmarca.getText());
        Equipo.setMODELO(this.txtmodelo.getText());
        if(verifica2){Equipo.crearEquipo();}
        
        if(OPAlter.esNumerico(txtabono.getText())&&OPAlter.esNumerico(txttotal.getText())&&Integer.parseInt(txttotal.getText())>=Integer.parseInt(txtabono.getText())){
            Ordendetrabajo.setABONO(Integer.parseInt(txtabono.getText()));
            Ordendetrabajo.setTOTAL(Integer.parseInt(txttotal.getText()));
        }else{
            Ordendetrabajo.setABONO(null);
            Ordendetrabajo.setTOTAL(null);
            lblabono.setForeground(Color.red);
            lbltotal.setForeground(Color.red);
            lblabono.setText("Abono    <=");
        }
        
        Ordendetrabajo.setCODLOCAL(Personal.getCODTIENDA());
        Ordendetrabajo.setDESCRIP_OBSER(txtaobservaciones.getText());
        Ordendetrabajo.setDIAGNO(txtadiagnostico.getText());
        Ordendetrabajo.setESTADO("Ingresado");
        if(combofalla.getSelectedIndex()!=0){Ordendetrabajo.setFALLA(String.valueOf(combofalla.getSelectedItem()));}
        else{Ordendetrabajo.setFALLA(null);}
        Ordendetrabajo.setFECHA_EN(spinnmodelo.getDate());
        Ordendetrabajo.setFECHA_ING(new Date());        
        if(Ordendetrabajo.crearOrden()){Ireport.crearOrden().setVisible(true); limpiar();}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combofalla;
    private javax.swing.JComboBox combotecnico;
    private javax.swing.JLabel lblabono;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbldiagnostico;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblfalla;
    private javax.swing.JLabel lblfechaentrega;
    private javax.swing.JLabel lblfechaingreso;
    private javax.swing.JLabel lblimei;
    private javax.swing.JLabel lblmarca;
    private javax.swing.JLabel lblmodelo;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblobservaciones;
    private javax.swing.JLabel lblrut;
    private javax.swing.JLabel lbltecnico;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JLabel lbltitulocliente;
    private javax.swing.JLabel lbltituloequipo;
    private javax.swing.JLabel lbltituloorden;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JPanel panelagregacliente;
    private javax.swing.JPanel panelagregaequipo;
    private javax.swing.JPanel panelagregaorden1;
    private javax.swing.JScrollPane scrolldiagnostico;
    private javax.swing.JScrollPane scrollobservaciones;
    private javax.swing.JSpinner spinnerfechaentrega;
    private javax.swing.JTextField txtabono;
    private javax.swing.JTextArea txtadiagnostico;
    private javax.swing.JTextArea txtaobservaciones;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdv;
    private javax.swing.JTextField txtfechaingreso;
    private javax.swing.JTextField txtimei;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtrut;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
