/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.OPAlter;
import Modelo.OrdenDeTrabajo;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class panelentregaorden extends javax.swing.JPanel {
private OrdenDeTrabajo Ordendetrabajo = new OrdenDeTrabajo();
private SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form panelentregaorden
     */
    public panelentregaorden() {
        initComponents();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtimei = new javax.swing.JTextField();
        comboguia = new javax.swing.JComboBox();
        lblcodigodeguia = new javax.swing.JLabel();
        lbltituloidentificador = new javax.swing.JLabel();
        lblimeiequipo = new javax.swing.JLabel();
        lblicono = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblfechaingreso = new javax.swing.JLabel();
        lblfechaentrega = new javax.swing.JLabel();
        txtfechaingreso = new javax.swing.JTextField();
        txtfechaentrega = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        lbltotal = new javax.swing.JLabel();
        txtabono = new javax.swing.JTextField();
        lblabono = new javax.swing.JLabel();
        lblestadoorden = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtimei.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtimeiFocusLost(evt);
            }
        });

        comboguia.setEditable(true);
        comboguia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboguiaItemStateChanged(evt);
            }
        });

        lblcodigodeguia.setText("Codigo de Orden");

        lbltituloidentificador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltituloidentificador.setText("Ingrese un identificador para acceder a la Orden");

        lblimeiequipo.setText("Imei Equipo");

        lblicono.setIcon(new javax.swing.ImageIcon("C:\\Users\\Diego\\Desktop\\PROYECTO TRABAJO DE TITULO\\InventarioServicioTecnico\\src\\Vista\\icon\\codigo-de-barras-escaneado-icono--psd_30-2603.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblimeiequipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtimei, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcodigodeguia, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(comboguia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbltituloidentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblicono, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblicono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbltituloidentificador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcodigodeguia)
                            .addComponent(lblimeiequipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboguia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtimei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblfechaingreso.setText("Fecha Ingreso");

        lblfechaentrega.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblfechaentrega.setText("Fecha Entrega");

        txtfechaingreso.setEditable(false);

        txtfechaentrega.setEditable(false);

        txttotal.setEditable(false);

        lbltotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltotal.setText("Total");

        txtabono.setEditable(false);

        lblabono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblabono.setText("Abono");

        lblestadoorden.setText("Estado de la Orden");

        txtestado.setEditable(false);
        txtestado.setText("Entregado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblfechaentrega, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtfechaingreso, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblfechaingreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfechaentrega))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtabono)
                    .addComponent(lblabono, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(lbltotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblestadoorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtestado))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfechaingreso)
                    .addComponent(lblabono)
                    .addComponent(lblestadoorden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtabono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfechaentrega)
                    .addComponent(lbltotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfechaentrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtimeiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtimeiFocusLost
        if(OPAlter.validaimei(txtimei.getText())){
            lblimeiequipo.setForeground(Color.BLACK);
            Ordendetrabajo.setIMEI(txtimei.getText().substring(0, 8));
            Ordendetrabajo.setSERIE(txtimei.getText().substring(8,txtimei.getText().length()));
            comboguia.setModel(Ordendetrabajo.buscarOrdenesImei());
        }else{
            limpiar();
            lblimeiequipo.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtimeiFocusLost

    private void comboguiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboguiaItemStateChanged
        try{
            Ordendetrabajo.setNUM_ORDEN(Integer.parseInt(String.valueOf(comboguia.getSelectedItem()).substring(6, String.valueOf(comboguia.getSelectedItem()).length())));
            Ordendetrabajo.setIMEI(String.valueOf(comboguia.getSelectedItem()));
            if(Ordendetrabajo.buscarOrden()){
                lblcodigodeguia.setForeground(Color.BLACK);
                this.txtabono.setText(String.valueOf(Ordendetrabajo.getABONO()));
                this.txtfechaingreso.setText(df.format(Ordendetrabajo.getFECHA_ING()));
                this.txttotal.setText(String.valueOf(Ordendetrabajo.getTOTAL()));
                this.lblestadoorden.setText("Estado de la Orden Actual("+Ordendetrabajo.getESTADO()+")");
                this.txtfechaentrega.setText(df.format(new Date()));
                txtabono.setEditable(true);
                txttotal.setEditable(true);
            }else{
                JOptionPane.showMessageDialog(null, "(ORDEN) La Orden no ha sido encontrada en la base de datos");
            }
        }catch(Exception e){
            lblcodigodeguia.setForeground(Color.red);
            limpiar();
        }
    }//GEN-LAST:event_comboguiaItemStateChanged

    public final void limpiar(){
               this.txtabono.setText("");
               this.txtfechaingreso.setText("");
               this.txttotal.setText("");
               this.lblestadoorden.setText("Estado de la Orden");
               this.txtfechaentrega.setText(df.format(new Date()));
               txtabono.setEditable(false);
               txttotal.setEditable(false);
               lblabono.setText("Abono");
               lblabono.setForeground(Color.BLACK);
               this.comboguia.setModel(new javax.swing.DefaultComboBoxModel(new String[] {""}));
               this.txtfechaentrega.setText(df.format(new Date()));
               lblimeiequipo.setForeground(Color.black);
    }
    
    public void entrega(){
        try{
            Ordendetrabajo.setNUM_ORDEN(Integer.parseInt(String.valueOf(comboguia.getSelectedItem()).substring(6, String.valueOf(comboguia.getSelectedItem()).length())));
            Ordendetrabajo.setIMEI(String.valueOf(comboguia.getSelectedItem()));
            if(Integer.parseInt(txtabono.getText())==Integer.parseInt(txttotal.getText())){
                Ordendetrabajo.setABONO(Integer.parseInt(txtabono.getText()));
                Ordendetrabajo.setTOTAL(Integer.parseInt(txttotal.getText()));
                Ordendetrabajo.setFECHA_EN(new Date());
                Ordendetrabajo.setESTADO("Entregado");
            }else{
                Ordendetrabajo.setABONO(null);
                Ordendetrabajo.setTOTAL(null);
                Ordendetrabajo.setFECHA_EN(null);
            }
            if(Ordendetrabajo.modificarOrdenA()){JOptionPane.showMessageDialog(null, "(ORDEN) La orden ha sido entregada Satisfactoriamente"); limpiar();}
            else{lblabono.setText("Abono = Total");lblabono.setForeground(Color.RED);}
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "(ORDEN) No se pudo modificar debido a un error en los datos ingresados");
            lblabono.setText("Abono = Total"); lblabono.setForeground(Color.RED);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboguia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblabono;
    private javax.swing.JLabel lblcodigodeguia;
    private javax.swing.JLabel lblestadoorden;
    private javax.swing.JLabel lblfechaentrega;
    private javax.swing.JLabel lblfechaingreso;
    private javax.swing.JLabel lblicono;
    private javax.swing.JLabel lblimeiequipo;
    private javax.swing.JLabel lbltituloidentificador;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTextField txtabono;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfechaentrega;
    private javax.swing.JTextField txtfechaingreso;
    private javax.swing.JTextField txtimei;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
