/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Personal;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Diego
 */
public class panelconfiguracion extends javax.swing.JPanel implements ChangeListener {
private int color;
private Color color1;
private Color color2;
private Personal Personal = new Personal();
    public panelconfiguracion() {
        initComponents();
        txttitulo.setDocument(new RestringeTextField(70));
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorcolor = new javax.swing.JColorChooser();
        lblsubtituloselectorcolor = new javax.swing.JLabel();
        lblsubtitulotitulo = new javax.swing.JLabel();
        txttitulo = new javax.swing.JTextField();
        lblcolor1 = new javax.swing.JLabel();
        lblcolor2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        lblsubtituloselectorcolor.setText("COLORES PANEL SUPERIOR");

        lblsubtitulotitulo.setText("TITULO PANEL SUPERIOR");

        lblcolor1.setText("            COLOR 1 (CLICK AQUI PARA EDITAR COLOR 1)");
        lblcolor1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblcolor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblcolor1MousePressed(evt);
            }
        });

        lblcolor2.setText("            COLOR 2 (CLICK AQUI PARA EDITAR COLOR 2)");
        lblcolor2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblcolor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblcolor2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectorcolor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsubtituloselectorcolor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblsubtitulotitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcolor1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(lblcolor2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsubtitulotitulo)
                    .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsubtituloselectorcolor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcolor1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(lblcolor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectorcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblcolor1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcolor1MousePressed
        color=1;
    }//GEN-LAST:event_lblcolor1MousePressed

    private void lblcolor2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcolor2MousePressed
        color=2;
    }//GEN-LAST:event_lblcolor2MousePressed

    public void modificar(){
        Personal.setTITULO(txttitulo.getText());
        color1=lblcolor1.getBackground();
        color2=lblcolor2.getBackground();
        Personal.setCOLORES(String.format("%03d,%03d,%03d-%03d,%03d,%03d",color1.getRed(),color1.getGreen(),color1.getBlue(), color2.getRed(), color2.getGreen(), color2.getBlue()));
        if(Personal.modificarConfiguracion()){
            JOptionPane.showMessageDialog(null, "[CONFIGURACION] Cambios realizados con Exito");
            limpiar();
        }
    }
    
    public final void limpiar(){
        Personal = new Personal();
        selectorcolor.getSelectionModel().addChangeListener(this);
        lblcolor1.setForeground(Color.WHITE);
        lblcolor1.setOpaque(true);
        lblcolor2.setOpaque(true);
        color=0;
        color1=null;
        color2=null;
        try{
            int a=Integer.parseInt(Personal.getCOLORES().substring(0, 3));
            int b=Integer.parseInt(Personal.getCOLORES().substring(4, 7));
            int c=Integer.parseInt(Personal.getCOLORES().substring(8, 11));
            int d=Integer.parseInt(Personal.getCOLORES().substring(12, 15));
            int e=Integer.parseInt(Personal.getCOLORES().substring(16, 19));
            int f=Integer.parseInt(Personal.getCOLORES().substring(20, 23));
            lblcolor1.setBackground(new Color(a,b,c));
            lblcolor2.setBackground(new Color(d,e,f));
        }catch(Exception e){}
        if(Personal.getTITULO()!=null){
            this.txttitulo.setText(Personal.getTITULO());
        }
        
    }
    
    @Override
    public void stateChanged(ChangeEvent e) {
        if(color == 1){lblcolor1.setBackground(selectorcolor.getColor()); color1=selectorcolor.getColor();}
        if(color == 2){lblcolor2.setBackground(selectorcolor.getColor()); color2=selectorcolor.getColor();}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblcolor1;
    private javax.swing.JLabel lblcolor2;
    private javax.swing.JLabel lblsubtituloselectorcolor;
    private javax.swing.JLabel lblsubtitulotitulo;
    private javax.swing.JColorChooser selectorcolor;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables

    
}
