/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cliente;
import Modelo.OPAlter;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class panelmodificarcliente extends javax.swing.JPanel {
private OPAlter OPAlter;
private Cliente Cliente = new Cliente();

    public panelmodificarcliente() {
        initComponents();
        txtcorreo.setDocument(new RestringeTextField(60));
        txtdireccion.setDocument(new RestringeTextField(60));
        txtnombre.setDocument(new RestringeTextField(60));
        txttelefono.setDocument(new RestringeTextField(9,true));
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txttelefono = new javax.swing.JTextField();
        lbldireccion = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lblrutcliente = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        lblcorreo = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        txtdv = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        setMaximumSize(new java.awt.Dimension(500, 270));
        setMinimumSize(new java.awt.Dimension(500, 270));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 270));

        txttelefono.setEditable(false);

        lbldireccion.setText("Direccion");

        lbltelefono.setText("Telefono");

        lblrutcliente.setText("Rut Cliente");

        txtcorreo.setEditable(false);

        txtdireccion.setEditable(false);

        lblcorreo.setText("Correo Electronico");

        txtrut.setEditable(false);
        txtrut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtrutFocusGained(evt);
            }
        });

        txtdv.setEditable(false);
        txtdv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdvFocusLost(evt);
            }
        });
        txtdv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdvKeyPressed(evt);
            }
        });

        lblnombre.setText("Nombre");

        txtnombre.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtrut, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblrutcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(txtnombre)
                            .addComponent(lblnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcorreo)
                            .addComponent(lblcorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                    .addComponent(txttelefono)
                    .addComponent(lbldireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdireccion))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblrutcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrut)
                    .addComponent(txtdv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblnombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcorreo)))
                .addGap(18, 18, 18)
                .addComponent(lbltelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbldireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtrutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrutFocusGained
        txtdv.requestFocus(true);
    }//GEN-LAST:event_txtrutFocusGained

    private void txtdvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdvFocusLost
        if (OPAlter.validarut(txtrut.getText(), txtdv.getText())) {
            Cliente.setRUT_C(txtrut.getText()+"-"+txtdv.getText());
            if (Cliente.buscarCliente()) {
                lblrutcliente.setText("Rut Cliente (Existente)");lblrutcliente.setForeground(Color.BLACK);
                txtnombre.setText(Cliente.getNOMBRE_C()); txtnombre.setEditable(true);
                txttelefono.setText(String.valueOf(Cliente.getTELEFONO())); txttelefono.setEditable(true);
                txtdireccion.setText(Cliente.getDIRECCION()); txtdireccion.setEditable(true);
                txtcorreo.setText(Cliente.getEMAIL()); txtcorreo.setEditable(true);
                //EXISTE=1;
            } else {
                lblrutcliente.setText("Rut Cliente (Nuevo)");lblrutcliente.setForeground(Color.GREEN.darker().darker());
                txtnombre.setText(""); txtnombre.setEditable(true);
                txttelefono.setText(""); txttelefono.setEditable(true);
                txtdireccion.setText(""); txtdireccion.setEditable(true);
                txtcorreo.setText(""); txtcorreo.setEditable(true);
                //EXISTE=2;
            }
        }else{lblrutcliente.setText("Rut Cliente (Invalido)");
            Cliente.setRUT_C(null);
            lblrutcliente.setForeground(Color.red);
            txtnombre.setText(""); txtnombre.setEditable(false);
            txttelefono.setText(""); txttelefono.setEditable(false);
            txtdireccion.setText(""); txtdireccion.setEditable(false);
            txtcorreo.setText(""); txtcorreo.setEditable(false);
            //EXISTE=0;
        }
    }//GEN-LAST:event_txtdvFocusLost

    private void txtdvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdvKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_BACK_SPACE)
        {
            try{
                txtdv.setText(String.valueOf(txtrut.getText().charAt(txtrut.getText().length()-1)));
                txtrut.setText(txtrut.getText().substring(0,txtrut.getText().length()-1));
            }catch(Exception e){txtdv.setText("");}
        }
        else if(OPAlter.esNumerico(String.valueOf(evt.getKeyChar())) || evt.getKeyChar()=='k'||evt.getKeyChar()=='K')
        {
            if(!txtdv.getText().isEmpty() && OPAlter.esNumerico(txtdv.getText())&& txtrut.getText().length()<=7)
            {
                txtrut.setText(txtrut.getText()+txtdv.getText());
            }
            if (String.valueOf(evt.getKeyChar()).matches("[0-9]") || evt.getKeyChar()=='k' || evt.getKeyChar()=='K')
            {
                txtdv.setText(String.valueOf(evt.getKeyChar()));
            }
        }
    }//GEN-LAST:event_txtdvKeyPressed

    public final void limpiar (){
        Cliente = new Cliente();
        txtrut.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        txtdv.requestFocus();
        lblrutcliente.setText("Rut Cliente");
        lblrutcliente.setForeground(Color.BLACK);
        txtrut.setText("");
        txtdv.setText("");
        txtnombre.setText(""); txtnombre.setEditable(false);
        txttelefono.setText(""); txttelefono.setEditable(false);
        txtdireccion.setText(""); txtdireccion.setEditable(false);
        txtcorreo.setText(""); txtcorreo.setEditable(false);
}
    
    public void agregarmodificar (){
        if(OPAlter.esNumerico(txttelefono.getText())){
        Cliente.setNOMBRE_C(txtnombre.getText());
        Cliente.setDIRECCION(txtdireccion.getText());
        Cliente.setEMAIL(txtcorreo.getText());
        Cliente.setTELEFONO(Integer.parseInt(txttelefono.getText()));}
        else{
        Cliente.setNOMBRE_C(txtnombre.getText());
        Cliente.setDIRECCION(txtdireccion.getText());
        Cliente.setEMAIL(txtcorreo.getText());
        Cliente.setTELEFONO(null);
        }
        if(Cliente.crearCliente()){JOptionPane.showMessageDialog(null, "Cliente Creado Correctamente"); limpiar();}
        else if(Cliente.modificarCliente()){JOptionPane.showMessageDialog(null, "Cliente Modificado Correctamente"); limpiar();}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblrutcliente;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtdv;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtrut;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
