/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.OPAlter;
import Modelo.Personal;
import Modelo.Tienda;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class panelmodificarmisdatos extends javax.swing.JPanel {
private Personal Personal = new Personal();
private Tienda Tienda = new Tienda();

    /**
     * Creates new form panelmodificarmisdatos
     */
    public panelmodificarmisdatos() {
        initComponents();
        txtayudacontrasena.setDocument(new RestringeTextField(70));
        txtcontrasena.setDocument(new RestringeTextField(10));
        txtnombre.setDocument(new RestringeTextField(60));
        txtnuevacontrasena.setDocument(new RestringeTextField(10));
        txtnuevacontrasena2.setDocument(new RestringeTextField(10));
        txttelefono.setDocument(new RestringeTextField(9,true));
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltienda = new javax.swing.JLabel();
        combotienda = new javax.swing.JComboBox();
        txttelefono = new javax.swing.JTextField();
        checkcontrasena = new javax.swing.JCheckBox();
        lblayudacontrasena = new javax.swing.JLabel();
        lblcontrasena = new javax.swing.JLabel();
        txtcontrasena = new javax.swing.JPasswordField();
        combopermiso = new javax.swing.JComboBox();
        txtayudacontrasena = new javax.swing.JTextField();
        lblpermiso = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lbltelefono = new javax.swing.JLabel();
        lblnuevacontrasena = new javax.swing.JLabel();
        lblnuevacontrasena2 = new javax.swing.JLabel();
        txtnuevacontrasena = new javax.swing.JPasswordField();
        txtnuevacontrasena2 = new javax.swing.JPasswordField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        lbltienda.setText("Tienda Actual()");
        lbltienda.setMaximumSize(new java.awt.Dimension(230, 14));
        lbltienda.setMinimumSize(new java.awt.Dimension(230, 14));
        lbltienda.setPreferredSize(new java.awt.Dimension(230, 14));

        combotienda.setEnabled(false);
        combotienda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combotiendaItemStateChanged(evt);
            }
        });

        txttelefono.setEditable(false);

        checkcontrasena.setText("Mostrar Contraseña");
        checkcontrasena.setMaximumSize(new java.awt.Dimension(121, 14));
        checkcontrasena.setMinimumSize(new java.awt.Dimension(121, 14));
        checkcontrasena.setPreferredSize(new java.awt.Dimension(121, 14));
        checkcontrasena.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkcontrasenaItemStateChanged(evt);
            }
        });

        lblayudacontrasena.setText("Ayuda Contraseña (datos para recordarla)");
        lblayudacontrasena.setMaximumSize(new java.awt.Dimension(230, 14));
        lblayudacontrasena.setMinimumSize(new java.awt.Dimension(230, 14));
        lblayudacontrasena.setPreferredSize(new java.awt.Dimension(230, 14));

        lblcontrasena.setText("Contraseña");
        lblcontrasena.setMaximumSize(new java.awt.Dimension(109, 14));
        lblcontrasena.setMinimumSize(new java.awt.Dimension(109, 14));
        lblcontrasena.setPreferredSize(new java.awt.Dimension(109, 14));

        txtcontrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcontrasenaFocusLost(evt);
            }
        });

        combopermiso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Permiso", "Tecnico", "Administrador" }));
        combopermiso.setEnabled(false);

        txtayudacontrasena.setEditable(false);

        lblpermiso.setText("Permiso tipo Administrador local o Tecnico local");
        lblpermiso.setMaximumSize(new java.awt.Dimension(230, 14));
        lblpermiso.setMinimumSize(new java.awt.Dimension(230, 14));
        lblpermiso.setPreferredSize(new java.awt.Dimension(230, 14));

        lblnombre.setText("Nombre");
        lblnombre.setMaximumSize(new java.awt.Dimension(230, 14));
        lblnombre.setMinimumSize(new java.awt.Dimension(230, 14));
        lblnombre.setPreferredSize(new java.awt.Dimension(230, 14));

        txtnombre.setEditable(false);

        lbltelefono.setText("Telefono");
        lbltelefono.setMaximumSize(new java.awt.Dimension(230, 14));
        lbltelefono.setMinimumSize(new java.awt.Dimension(230, 14));
        lbltelefono.setPreferredSize(new java.awt.Dimension(230, 14));

        lblnuevacontrasena.setText("Nueva Contraseña");

        lblnuevacontrasena2.setText("Repetir Nueva Constraseña");

        txtnuevacontrasena.setEditable(false);

        txtnuevacontrasena2.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombre)
                                    .addComponent(lblnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbltelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttelefono))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblayudacontrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtayudacontrasena))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtcontrasena)
                            .addComponent(txtnuevacontrasena2)
                            .addComponent(txtnuevacontrasena)
                            .addComponent(lblnuevacontrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblnuevacontrasena2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combopermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combotienda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblpermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbltienda, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(txtcontrasena))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnuevacontrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(txtnuevacontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnuevacontrasena2)
                    .addComponent(lblayudacontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnuevacontrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtayudacontrasena))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltienda, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combopermiso)
                    .addComponent(combotienda, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcontrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcontrasenaFocusLost
        if(Personal.getCONTRASENA().equals(String.valueOf(txtcontrasena.getPassword()))){
            txtnombre.setEditable(true);
            txttelefono.setEditable(true);
            combotienda.setEnabled(true);
            combopermiso.setEnabled(true);
            txtnuevacontrasena.setEditable(true);
            txtnuevacontrasena2.setEditable(true);
            txtayudacontrasena.setEditable(true);
        }
        else{
            limpiar();
        }
    }//GEN-LAST:event_txtcontrasenaFocusLost

    private void combotiendaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combotiendaItemStateChanged
        if(combotienda.getSelectedIndex()==0){
            this.lbltienda.setText("Tienda Actual()");
            this.lbltienda.setForeground(Color.red);
            }
            else{
            this.lbltienda.setForeground(Color.BLACK);
            this.lbltienda.setText("Tienda Actual( "+Tienda.getNOMBRE()+" )");
            }
    }//GEN-LAST:event_combotiendaItemStateChanged

    private void checkcontrasenaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkcontrasenaItemStateChanged
        if(evt.getStateChange()==1){
            txtcontrasena.setEchoChar('\0');
            txtnuevacontrasena.setEchoChar('\0');
            txtnuevacontrasena2.setEchoChar('\0');
        }
        else{
            txtcontrasena.setEchoChar('*');
            txtnuevacontrasena.setEchoChar('*');
            txtnuevacontrasena2.setEchoChar('*');
        }
    }//GEN-LAST:event_checkcontrasenaItemStateChanged

    public void modificar(){
        if((String.valueOf(txtcontrasena.getPassword()).equals(Personal.getCONTRASENA()))&&(String.valueOf(txtnuevacontrasena.getPassword()).equals(String.valueOf(txtnuevacontrasena2.getPassword())))&&(OPAlter.esNumerico(txttelefono.getText()))){
            if("".equals(String.valueOf(txtnuevacontrasena.getPassword()))||String.valueOf(txtnuevacontrasena.getPassword())==null){
                Personal.setMCONTRASENA(Personal.getCONTRASENA());
            }else{
                Personal.setMCONTRASENA(String.valueOf(txtnuevacontrasena.getPassword()));
            }
            Personal.setMTELEFONO(Integer.parseInt(txttelefono.getText()));
            Personal.setMAYUDACONTRASENA(txtayudacontrasena.getText());
            Personal.setMNOMBRE_P(txtnombre.getText());
            Personal.setMRUT_P(Personal.getRUT_P());
            if(combopermiso.getSelectedIndex()==0){Personal.setMPERMISO(Personal.getPERMISO());}
            if(combopermiso.getSelectedIndex()==1){Personal.setMPERMISO("T");}
            if(combopermiso.getSelectedIndex()==2){Personal.setMPERMISO("A");}
            if(combotienda.getSelectedIndex()!=0){Personal.setMCODTIENDA(((Tienda)combotienda.getSelectedItem()).getCODTIENDA());}
            else{Personal.setMCODTIENDA(Personal.getCODTIENDA());}
            if(Personal.modificarMisDatos()){JOptionPane.showMessageDialog(null, "Cambios Realizados Con Exito");}
            else{JOptionPane.showMessageDialog(null, "Error al Realizar Cambios");}
        }else{
            JOptionPane.showMessageDialog(null, "Error al Realizar Cambios");
        }
    }
    
    public final void limpiar(){
        Personal = new Personal();
        Tienda = new Tienda();
        Tienda.setCODTIENDA(Personal.getCODTIENDA());
        Tienda = Tienda.buscarTienda(Tienda);
        combotienda.setModel(Tienda.comboTiendas());
        combotienda.setEnabled(false);
        combotienda.setSelectedIndex(0);
        lbltienda.setText("Tienda Actual("+Tienda.getNOMBRE()+")");
        this.txtayudacontrasena.setEditable(false);
        this.txtayudacontrasena.setText(Personal.getAYUDACONTRASENA());
        this.txtcontrasena.setText("");
        this.txtnuevacontrasena.setText("");
        this.txtnuevacontrasena2.setText("");
        this.txtnuevacontrasena.setEditable(false);
        this.txtnuevacontrasena2.setEditable(false);
        this.txtnombre.setEditable(false);
        this.txtnombre.setText(Personal.getNOMBRE_P());
        this.txttelefono.setEditable(false);
        this.txttelefono.setText(String.valueOf(Personal.getTELEFONO()));
        this.lbltienda.setForeground(Color.BLACK);
        this.lblpermiso.setText("Permiso");
        this.lblpermiso.setForeground(Color.BLACK);
        this.combopermiso.setEnabled(false);
        this.combopermiso.setSelectedIndex(0);
        this.lbltelefono.setForeground(Color.BLACK);
        if("T".equals(Personal.getPERMISO())){
            combopermiso.setVisible(false); combotienda.setVisible(false);
            lblpermiso.setVisible(false); lbltienda.setVisible(false);
        }
        if("00000000-0".equals(Personal.getRUT_P())){combopermiso.setVisible(false); lblpermiso.setVisible(false);}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkcontrasena;
    private javax.swing.JComboBox combopermiso;
    private javax.swing.JComboBox combotienda;
    private javax.swing.JLabel lblayudacontrasena;
    private javax.swing.JLabel lblcontrasena;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnuevacontrasena;
    private javax.swing.JLabel lblnuevacontrasena2;
    private javax.swing.JLabel lblpermiso;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JLabel lbltienda;
    private javax.swing.JTextField txtayudacontrasena;
    private javax.swing.JPasswordField txtcontrasena;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtnuevacontrasena;
    private javax.swing.JPasswordField txtnuevacontrasena2;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
