/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Ireport;
import Modelo.OPAlter;
import Modelo.Tienda;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author Diego
 */
public class panelinformetienda extends javax.swing.JPanel {
private Tienda Tienda;
private Ireport Ireport;
private SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form panelinformetienda
     */
    public panelinformetienda() {
        Tienda = new Tienda();
        Ireport = new Ireport();
        initComponents();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        paneltiendas = new javax.swing.JPanel();
        lbltiendas = new javax.swing.JLabel();
        combotiendas = new javax.swing.JComboBox();
        panelagrupa = new javax.swing.JPanel();
        lblcategoria = new javax.swing.JLabel();
        separadoragrupa = new javax.swing.JSeparator();
        checkplacas = new javax.swing.JCheckBox();
        checkflex = new javax.swing.JCheckBox();
        checkpantalla = new javax.swing.JCheckBox();
        lblfalla = new javax.swing.JLabel();
        checkauricular = new javax.swing.JCheckBox();
        checklimpieza = new javax.swing.JCheckBox();
        checkdesbloqueo = new javax.swing.JCheckBox();
        checkotros = new javax.swing.JCheckBox();
        checkprocesando = new javax.swing.JCheckBox();
        checkingresado = new javax.swing.JCheckBox();
        checkentregado = new javax.swing.JCheckBox();
        checkterminado = new javax.swing.JCheckBox();
        lblestados = new javax.swing.JLabel();
        separadorincluye = new javax.swing.JSeparator();
        radiocliente = new javax.swing.JRadioButton();
        radiopersonal = new javax.swing.JRadioButton();
        radioequipos = new javax.swing.JRadioButton();
        radiofabricante = new javax.swing.JRadioButton();
        radiomodelo = new javax.swing.JRadioButton();
        radiotodos = new javax.swing.JRadioButton();
        panelorden = new javax.swing.JPanel();
        lblcantidad = new javax.swing.JLabel();
        spinnercantidad = new javax.swing.JSpinner();
        panelfechas = new javax.swing.JPanel();
        radioestemes1 = new javax.swing.JRadioButton();
        radioesteaño1 = new javax.swing.JRadioButton();
        radioentre1 = new javax.swing.JRadioButton();
        lbla = new javax.swing.JLabel();
        spinnerfechaini1 = new javax.swing.JSpinner();
        spinnerfechafin1 = new javax.swing.JSpinner();
        separadorfechas = new javax.swing.JSeparator();
        spinnerfechafin2 = new javax.swing.JSpinner();
        lbla1 = new javax.swing.JLabel();
        spinnerfechaini2 = new javax.swing.JSpinner();
        radioentre2 = new javax.swing.JRadioButton();
        radioesteaño2 = new javax.swing.JRadioButton();
        radioestemes2 = new javax.swing.JRadioButton();
        radiofechaingreso = new javax.swing.JRadioButton();
        radiofechaentrega = new javax.swing.JRadioButton();
        radiohoy1 = new javax.swing.JRadioButton();
        radiohoy2 = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        paneltiendas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltiendas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltiendas.setText("Tienda Para generar el Informe");

        javax.swing.GroupLayout paneltiendasLayout = new javax.swing.GroupLayout(paneltiendas);
        paneltiendas.setLayout(paneltiendasLayout);
        paneltiendasLayout.setHorizontalGroup(
            paneltiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltiendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneltiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltiendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combotiendas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneltiendasLayout.setVerticalGroup(
            paneltiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltiendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltiendas)
                .addGap(18, 18, 18)
                .addComponent(combotiendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelagrupa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblcategoria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcategoria.setText("<html><body>Agrupar Resultados por<br> Categoria:</body></html>");

        separadoragrupa.setOrientation(javax.swing.SwingConstants.VERTICAL);

        checkplacas.setSelected(true);
        checkplacas.setText("Cambio/Reparacion Placas");

        checkflex.setSelected(true);
        checkflex.setText("Cambio/Reparacion de Flex");

        checkpantalla.setSelected(true);
        checkpantalla.setText("Quiebre Pantalla");

        lblfalla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblfalla.setText("<html><body>Seleccione Fallas<br>que se incluiran en el informe</body></html>");

        checkauricular.setSelected(true);
        checkauricular.setText("Cambio Auricular Microfono");

        checklimpieza.setSelected(true);
        checklimpieza.setText("Limpieza / Zulfurado / etc.");

        checkdesbloqueo.setSelected(true);
        checkdesbloqueo.setText("Desbloqueo");

        checkotros.setSelected(true);
        checkotros.setText("Otros");

        checkprocesando.setSelected(true);
        checkprocesando.setText("Procesando");

        checkingresado.setSelected(true);
        checkingresado.setText("Ingresado");

        checkentregado.setText("Entregado");

        checkterminado.setText("Terminado");

        lblestados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblestados.setText("<html><body>Seleccione Estados de la Orden<br>que se incluiran en el informe</body></html>");

        separadorincluye.setOrientation(javax.swing.SwingConstants.VERTICAL);

        buttonGroup5.add(radiocliente);
        radiocliente.setSelected(true);
        radiocliente.setText("Clientes");

        buttonGroup5.add(radiopersonal);
        radiopersonal.setText("Personal");

        buttonGroup5.add(radioequipos);
        radioequipos.setText("Equipos");
        radioequipos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioequiposItemStateChanged(evt);
            }
        });

        buttonGroup6.add(radiofabricante);
        radiofabricante.setSelected(true);
        radiofabricante.setText("Fabricante");
        radiofabricante.setEnabled(false);

        buttonGroup6.add(radiomodelo);
        radiomodelo.setText("Modelo");
        radiomodelo.setEnabled(false);

        buttonGroup5.add(radiotodos);
        radiotodos.setText("No Agrupar");

        javax.swing.GroupLayout panelagrupaLayout = new javax.swing.GroupLayout(panelagrupa);
        panelagrupa.setLayout(panelagrupaLayout);
        panelagrupaLayout.setHorizontalGroup(
            panelagrupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelagrupaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelagrupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(radiocliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radiopersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioequipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radiotodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelagrupaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelagrupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radiofabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radiomodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addComponent(separadoragrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panelagrupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkotros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkdesbloqueo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblfalla)
                    .addComponent(checkpantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkflex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkauricular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checklimpieza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkplacas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(separadorincluye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(panelagrupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkprocesando)
                    .addComponent(checkterminado)
                    .addComponent(lblestados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkingresado)
                    .addComponent(checkentregado))
                .addGap(71, 71, 71))
        );
        panelagrupaLayout.setVerticalGroup(
            panelagrupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelagrupaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelagrupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelagrupaLayout.createSequentialGroup()
                        .addComponent(lblestados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkingresado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkprocesando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkterminado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkentregado))
                    .addGroup(panelagrupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(separadoragrupa)
                        .addComponent(separadorincluye)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelagrupaLayout.createSequentialGroup()
                            .addGroup(panelagrupaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelagrupaLayout.createSequentialGroup()
                                    .addComponent(lblfalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checkpantalla)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checkflex)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checkplacas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checkauricular)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checklimpieza)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checkdesbloqueo))
                                .addGroup(panelagrupaLayout.createSequentialGroup()
                                    .addComponent(lblcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radiocliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radiopersonal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radioequipos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radiofabricante)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radiomodelo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radiotodos)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(checkotros))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelorden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblcantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcantidad.setText("<html><body>Sobre la siguiente cantidad<br> de Ordenes se Incluiran los <br>Resultados por Categoria</body></html>");

        spinnercantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        javax.swing.GroupLayout panelordenLayout = new javax.swing.GroupLayout(panelorden);
        panelorden.setLayout(panelordenLayout);
        panelordenLayout.setHorizontalGroup(
            panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelordenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(spinnercantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        panelordenLayout.setVerticalGroup(
            panelordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelordenLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelordenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spinnercantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        panelfechas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(radioestemes1);
        radioestemes1.setSelected(true);
        radioestemes1.setText("Este Mes");

        buttonGroup1.add(radioesteaño1);
        radioesteaño1.setText("Este Año");

        buttonGroup1.add(radioentre1);
        radioentre1.setText("Entre");
        radioentre1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioentre1ItemStateChanged(evt);
            }
        });

        lbla.setText("A");

        spinnerfechaini1.setModel(new javax.swing.SpinnerDateModel());
        spinnerfechaini1.setEnabled(false);

        spinnerfechafin1.setModel(new javax.swing.SpinnerDateModel());
        spinnerfechafin1.setEnabled(false);

        separadorfechas.setOrientation(javax.swing.SwingConstants.VERTICAL);

        spinnerfechafin2.setModel(new javax.swing.SpinnerDateModel());
        spinnerfechafin2.setEnabled(false);

        lbla1.setText("A");

        spinnerfechaini2.setModel(new javax.swing.SpinnerDateModel());
        spinnerfechaini2.setEnabled(false);

        buttonGroup2.add(radioentre2);
        radioentre2.setText("Entre");
        radioentre2.setEnabled(false);
        radioentre2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioentre2ItemStateChanged(evt);
            }
        });

        buttonGroup2.add(radioesteaño2);
        radioesteaño2.setText("Este Año");
        radioesteaño2.setEnabled(false);

        buttonGroup2.add(radioestemes2);
        radioestemes2.setSelected(true);
        radioestemes2.setText("Este Mes");
        radioestemes2.setEnabled(false);

        buttonGroup3.add(radiofechaingreso);
        radiofechaingreso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radiofechaingreso.setSelected(true);
        radiofechaingreso.setText("Filtro por fecha de Ingreso");
        radiofechaingreso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radiofechaingresoItemStateChanged(evt);
            }
        });

        buttonGroup3.add(radiofechaentrega);
        radiofechaentrega.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radiofechaentrega.setText("Filtro por fecha de Entrega");
        radiofechaentrega.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radiofechaentregaItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radiohoy1);
        radiohoy1.setText("Hoy");

        buttonGroup2.add(radiohoy2);
        radiohoy2.setText("Hoy");
        radiohoy2.setEnabled(false);

        javax.swing.GroupLayout panelfechasLayout = new javax.swing.GroupLayout(panelfechas);
        panelfechas.setLayout(panelfechasLayout);
        panelfechasLayout.setHorizontalGroup(
            panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radiofechaingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelfechasLayout.createSequentialGroup()
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radioestemes1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioesteaño1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelfechasLayout.createSequentialGroup()
                                .addComponent(radioentre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerfechaini1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radiohoy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerfechafin1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71)
                .addComponent(separadorfechas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radiofechaentrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelfechasLayout.createSequentialGroup()
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(radioestemes2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioesteaño2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelfechasLayout.createSequentialGroup()
                                .addComponent(radioentre2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerfechaini2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelfechasLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lbla1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerfechafin2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(panelfechasLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(radiohoy2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        panelfechasLayout.setVerticalGroup(
            panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorfechas)
                    .addGroup(panelfechasLayout.createSequentialGroup()
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelfechasLayout.createSequentialGroup()
                                .addComponent(radiofechaingreso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioestemes1)
                                    .addComponent(radiohoy1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioesteaño1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioentre1)
                                    .addComponent(lbla)
                                    .addComponent(spinnerfechaini1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerfechafin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelfechasLayout.createSequentialGroup()
                                .addComponent(radiofechaentrega)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioestemes2)
                                    .addComponent(radiohoy2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioesteaño2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioentre2)
                                    .addComponent(lbla1)
                                    .addComponent(spinnerfechaini2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerfechafin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneltiendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelagrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(panelfechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneltiendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelagrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelfechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radiofechaingresoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radiofechaingresoItemStateChanged
        if(evt.getStateChange()==1){
            radioestemes1.setEnabled(true);
            radioesteaño1.setEnabled(true);
            radioentre1.setEnabled(true);
            radiohoy1.setEnabled(true);
            spinnerfechaini2.setEnabled(false);
            spinnerfechafin2.setEnabled(false);
            radioestemes2.setEnabled(false);
            radioesteaño2.setEnabled(false);
            radioentre2.setEnabled(false);
            radiohoy2.setEnabled(false);
            if(radioentre1.isSelected()){
                spinnerfechaini1.setEnabled(true);
                spinnerfechafin1.setEnabled(true);
            }
        }
    }//GEN-LAST:event_radiofechaingresoItemStateChanged

    private void radiofechaentregaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radiofechaentregaItemStateChanged
        if(evt.getStateChange()==1){
            radioestemes2.setEnabled(true);
            radioesteaño2.setEnabled(true);
            radioentre2.setEnabled(true);
            radiohoy2.setEnabled(true);
            spinnerfechaini1.setEnabled(false);
            spinnerfechafin1.setEnabled(false);
            radioestemes1.setEnabled(false);
            radioesteaño1.setEnabled(false);
            radioentre1.setEnabled(false);
            radiohoy1.setEnabled(false);
            if(radioentre2.isSelected()){
                spinnerfechaini2.setEnabled(true);
                spinnerfechafin2.setEnabled(true);
            }
        }
    }//GEN-LAST:event_radiofechaentregaItemStateChanged

    private void radioentre1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioentre1ItemStateChanged
        if(evt.getStateChange()==1){
            spinnerfechaini1.setEnabled(true);
            spinnerfechafin1.setEnabled(true);
        }else{
            spinnerfechaini1.setEnabled(false);
            spinnerfechafin1.setEnabled(false);
        }
    }//GEN-LAST:event_radioentre1ItemStateChanged

    private void radioentre2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioentre2ItemStateChanged
        if(evt.getStateChange()==1){
            spinnerfechaini2.setEnabled(true);
            spinnerfechafin2.setEnabled(true);
        }else{
            spinnerfechaini2.setEnabled(false);
            spinnerfechafin2.setEnabled(false);
        }
    }//GEN-LAST:event_radioentre2ItemStateChanged

    private void radioequiposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioequiposItemStateChanged
        if(evt.getStateChange()==1){
            radiofabricante.setEnabled(true);
            radiomodelo.setEnabled(true);
        }else{
            radiofabricante.setEnabled(false);
            radiomodelo.setEnabled(false);
        }
    }//GEN-LAST:event_radioequiposItemStateChanged

    public void mostrarInforme(){
        String fechaini1="", fechafin1="", fechaini2="", fechafin2="";
        String fecha="";
        String falla1="", falla2="", falla3="", falla4="", falla5="", falla6="", falla7="";
        String estado1="", estado2="", estado3="", estado4="";
        Integer cantidad, codtienda;
        if(radiofechaingreso.isSelected()){
            fecha="FECHA DE INGRESO";
            fechafin1=df.format(new Date());
            if(radioestemes1.isSelected()){
                fechaini1=df.format(OPAlter.restamesano(new Date(), "mes", -1));
            }
            if(radioesteaño1.isSelected()){
                fechaini1=df.format(OPAlter.restamesano(new Date(), "año", -1));
            }
            if(radiohoy1.isSelected()){
                fechaini1=df.format(OPAlter.restamesano(new Date(), "dia", 0));
            }
            if(radioentre1.isSelected()){
                    fechaini1=df.format(spinnerfechaini1.getModel().getValue());
                    fechafin1=df.format(spinnerfechafin1.getModel().getValue());
            }
        }
        if(radiofechaentrega.isSelected()){
            fecha="FECHA DE ENTREGA";
            fechafin2=df.format(new Date());
            if(radioestemes2.isSelected()){
                fechaini2=df.format(OPAlter.restamesano(new Date(), "mes", -1));
            }
            if(radioesteaño2.isSelected()){
                fechaini2=df.format(OPAlter.restamesano(new Date(), "año", -1));
            }
            if(radiohoy2.isSelected()){
                fechaini2=df.format(OPAlter.restamesano(new Date(), "dia", 0));
            }
            if(radioentre2.isSelected()){
                    fechaini2=df.format(spinnerfechaini2.getModel().getValue());
                    fechafin2=df.format(spinnerfechafin2.getModel().getValue());                
            }
        }
        if(checkpantalla.isSelected()){falla1=checkpantalla.getText();}
        if(checkflex.isSelected()){falla2=checkflex.getText();}
        if(checkplacas.isSelected()){falla3=checkplacas.getText();}
        if(checkauricular.isSelected()){falla4=checkauricular.getText();}
        if(checklimpieza.isSelected()){falla5=checklimpieza.getText();}
        if(checkdesbloqueo.isSelected()){falla6=checkdesbloqueo.getText();}
        if(checkotros.isSelected()){falla7=checkotros.getText();}
        if(checkingresado.isSelected()){estado1=checkingresado.getText();}
        if(checkprocesando.isSelected()){estado2=checkprocesando.getText();}
        if(checkterminado.isSelected()){estado3=checkterminado.getText();}
        if(checkentregado.isSelected()){estado4=checkentregado.getText();}
        cantidad=Integer.parseInt(String.valueOf(spinnercantidad.getValue()));
        if(combotiendas.getSelectedIndex()!=0){
            codtienda=((Tienda)combotiendas.getSelectedItem()).getCODTIENDA();
            if(radiocliente.isSelected()){
                Ireport.informeTienda_Cliente(falla1, falla2, falla3, falla4, falla5, falla6, falla7, estado1, estado2, estado3, estado4, fechaini1, fechafin1, fechaini2, fechafin2, codtienda, fecha, cantidad).setVisible(true);
            }
            if(radiopersonal.isSelected()){
                Ireport.informeTienda_Personal(falla1, falla2, falla3, falla4, falla5, falla6, falla7, estado1, estado2, estado3, estado4, fechaini1, fechafin1, fechaini2, fechafin2, codtienda, fecha, cantidad).setVisible(true);
            }
            if(radioequipos.isSelected()){
                if(radiofabricante.isSelected()){Ireport.informeTienda_Marca(falla1, falla2, falla3, falla4, falla5, falla6, falla7, estado1, estado2, estado3, estado4, fechaini1, fechafin1, fechaini2, fechafin2, codtienda, fecha, cantidad).setVisible(true);}
                if(radiomodelo.isSelected()){Ireport.informeTienda_Modelo(falla1, falla2, falla3, falla4, falla5, falla6, falla7, estado1, estado2, estado3, estado4, fechaini1, fechafin1, fechaini2, fechafin2, codtienda, fecha, cantidad).setVisible(true);}
            }
            if(radiotodos.isSelected()){Ireport.informeTienda_Todos(falla1, falla2, falla3, falla4, falla5, falla6, falla7, estado1, estado2, estado3, estado4, fechaini1, fechafin1, fechaini2, fechafin2, codtienda, fecha, cantidad).setVisible(true);}
        }else{JOptionPane.showMessageDialog(null, "(INFORME) Debe seleccionar una Tienda Valida");}
    }
    public final void limpiar(){
        JSpinner.DateEditor editor1= new JSpinner.DateEditor(spinnerfechaini1, "dd/MM/yyyy");
        JFormattedTextField ftf1 = editor1.getTextField();
        ftf1.setEditable(false);
        spinnerfechaini1.setEditor(editor1);
        JSpinner.DateEditor editor2= new JSpinner.DateEditor(spinnerfechafin1, "dd/MM/yyyy");
        JFormattedTextField ftf2 = editor2.getTextField();
        ftf2.setEditable(false);
        spinnerfechafin1.setEditor(editor2);
        JSpinner.DateEditor editor3= new JSpinner.DateEditor(spinnerfechaini2, "dd/MM/yyyy");
        JFormattedTextField ftf3 = editor3.getTextField();
        ftf3.setEditable(false);
        spinnerfechaini2.setEditor(editor3);
        JSpinner.DateEditor editor4= new JSpinner.DateEditor(spinnerfechafin2, "dd/MM/yyyy");
        JFormattedTextField ftf4 = editor4.getTextField();
        ftf4.setEditable(false);
        spinnerfechafin2.setEditor(editor4);
        combotiendas.setModel(Tienda.comboTiendas());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JCheckBox checkauricular;
    private javax.swing.JCheckBox checkdesbloqueo;
    private javax.swing.JCheckBox checkentregado;
    private javax.swing.JCheckBox checkflex;
    private javax.swing.JCheckBox checkingresado;
    private javax.swing.JCheckBox checklimpieza;
    private javax.swing.JCheckBox checkotros;
    private javax.swing.JCheckBox checkpantalla;
    private javax.swing.JCheckBox checkplacas;
    private javax.swing.JCheckBox checkprocesando;
    private javax.swing.JCheckBox checkterminado;
    private javax.swing.JComboBox combotiendas;
    private javax.swing.JLabel lbla;
    private javax.swing.JLabel lbla1;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JLabel lblcategoria;
    private javax.swing.JLabel lblestados;
    private javax.swing.JLabel lblfalla;
    private javax.swing.JLabel lbltiendas;
    private javax.swing.JPanel panelagrupa;
    private javax.swing.JPanel panelfechas;
    private javax.swing.JPanel panelorden;
    private javax.swing.JPanel paneltiendas;
    private javax.swing.JRadioButton radiocliente;
    private javax.swing.JRadioButton radioentre1;
    private javax.swing.JRadioButton radioentre2;
    private javax.swing.JRadioButton radioequipos;
    private javax.swing.JRadioButton radioesteaño1;
    private javax.swing.JRadioButton radioesteaño2;
    private javax.swing.JRadioButton radioestemes1;
    private javax.swing.JRadioButton radioestemes2;
    private javax.swing.JRadioButton radiofabricante;
    private javax.swing.JRadioButton radiofechaentrega;
    private javax.swing.JRadioButton radiofechaingreso;
    private javax.swing.JRadioButton radiohoy1;
    private javax.swing.JRadioButton radiohoy2;
    private javax.swing.JRadioButton radiomodelo;
    private javax.swing.JRadioButton radiopersonal;
    private javax.swing.JRadioButton radiotodos;
    private javax.swing.JSeparator separadoragrupa;
    private javax.swing.JSeparator separadorfechas;
    private javax.swing.JSeparator separadorincluye;
    private javax.swing.JSpinner spinnercantidad;
    private javax.swing.JSpinner spinnerfechafin1;
    private javax.swing.JSpinner spinnerfechafin2;
    private javax.swing.JSpinner spinnerfechaini1;
    private javax.swing.JSpinner spinnerfechaini2;
    // End of variables declaration//GEN-END:variables
}
