/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.OPAlter;
import Modelo.Personal;
import Modelo.Tienda;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class panelmodificarpersonal extends javax.swing.JPanel {
private Personal Personal = new Personal();
private Tienda Tienda = new Tienda();
    /**
     * Creates new form panelmodificarpersonal
     */
    public panelmodificarpersonal() {
        initComponents();
        txtayudacontrasena.setDocument(new RestringeTextField(70));
        txtcontrasena.setDocument(new RestringeTextField(10));
        txtnombre.setDocument(new RestringeTextField(60));
        txttelefono.setDocument(new RestringeTextField(9, true));
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblayudacontrasena = new javax.swing.JLabel();
        checkcontrasena = new javax.swing.JCheckBox();
        combotienda = new javax.swing.JComboBox();
        lbltienda = new javax.swing.JLabel();
        txtcontrasena = new javax.swing.JPasswordField();
        lblcontrasena = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        lbltelefono = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        lblpermiso = new javax.swing.JLabel();
        combopermiso = new javax.swing.JComboBox();
        txtayudacontrasena = new javax.swing.JTextField();
        lblcombotecnico = new javax.swing.JLabel();
        combotecnico = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        setMaximumSize(new java.awt.Dimension(500, 270));
        setMinimumSize(new java.awt.Dimension(500, 270));

        lblayudacontrasena.setText("Ayuda Contraseña (datos para recordarla)");
        lblayudacontrasena.setMaximumSize(new java.awt.Dimension(230, 14));
        lblayudacontrasena.setMinimumSize(new java.awt.Dimension(230, 14));
        lblayudacontrasena.setPreferredSize(new java.awt.Dimension(230, 14));

        checkcontrasena.setText("Mostrar Contraseña");
        checkcontrasena.setMaximumSize(new java.awt.Dimension(121, 14));
        checkcontrasena.setMinimumSize(new java.awt.Dimension(121, 14));
        checkcontrasena.setPreferredSize(new java.awt.Dimension(121, 14));
        checkcontrasena.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkcontrasenaItemStateChanged(evt);
            }
        });

        combotienda.setEnabled(false);
        combotienda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combotiendaItemStateChanged(evt);
            }
        });

        lbltienda.setText("Tienda Actual()");
        lbltienda.setMaximumSize(new java.awt.Dimension(230, 14));
        lbltienda.setMinimumSize(new java.awt.Dimension(230, 14));
        lbltienda.setPreferredSize(new java.awt.Dimension(230, 14));

        txtcontrasena.setEditable(false);

        lblcontrasena.setText("Contraseña");
        lblcontrasena.setMaximumSize(new java.awt.Dimension(109, 14));
        lblcontrasena.setMinimumSize(new java.awt.Dimension(109, 14));
        lblcontrasena.setPreferredSize(new java.awt.Dimension(109, 14));

        txttelefono.setEditable(false);

        lbltelefono.setText("Telefono");
        lbltelefono.setMaximumSize(new java.awt.Dimension(230, 14));
        lbltelefono.setMinimumSize(new java.awt.Dimension(230, 14));
        lbltelefono.setPreferredSize(new java.awt.Dimension(230, 14));

        txtnombre.setEditable(false);

        lblnombre.setText("Nombre");
        lblnombre.setMaximumSize(new java.awt.Dimension(230, 14));
        lblnombre.setMinimumSize(new java.awt.Dimension(230, 14));
        lblnombre.setPreferredSize(new java.awt.Dimension(230, 14));

        lblpermiso.setText("Permiso tipo Administrador local o Tecnico local");
        lblpermiso.setMaximumSize(new java.awt.Dimension(230, 14));
        lblpermiso.setMinimumSize(new java.awt.Dimension(230, 14));
        lblpermiso.setPreferredSize(new java.awt.Dimension(230, 14));

        combopermiso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Permiso", "Tecnico", "Administrador" }));
        combopermiso.setEnabled(false);

        txtayudacontrasena.setEditable(false);

        lblcombotecnico.setText("Seleccionar Tecnico A Modificar");

        combotecnico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combotecnicoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltienda, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combotienda, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combotecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcombotecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblpermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combopermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblayudacontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtayudacontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcombotecnico, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combotecnico, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnombre)
                            .addComponent(txtcontrasena))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblayudacontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttelefono)
                            .addComponent(txtayudacontrasena))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblpermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combotienda)
                            .addComponent(combopermiso))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combotecnicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combotecnicoItemStateChanged
        if(combotecnico.getSelectedIndex()==0){
            this.lblcombotecnico.setText("Seleccionar Tecnico A Modificar (Invalido)");
            this.lblcombotecnico.setForeground(Color.red);
            //Personal.setMRUT_P(null);
            limpiar();
            
        }
        else{
            
            lblcombotecnico.setForeground(Color.BLACK);
            lblcombotecnico.setText("Seleccionar Tecnico A Modificar");
            Personal.setMRUT_P(String.valueOf(Personal.getListmodelrut().getElementAt(combotecnico.getSelectedIndex())));
            Personal.buscarPersonal();
            Tienda.setCODTIENDA(Personal.getMCODTIENDA());
            Tienda = Tienda.buscarTienda(Tienda);
            lbltienda.setText("Tienda Actual("+Tienda.getNOMBRE()+")");
            txtnombre.setText(Personal.getMNOMBRE_P()); txtnombre.setEditable(true);
            txttelefono.setText(String.valueOf(Personal.getMTELEFONO())); txttelefono.setEditable(true);
            txtcontrasena.setText(Personal.getMCONTRASENA()); txtcontrasena.setEditable(true);
            txtayudacontrasena.setText(Personal.getMAYUDACONTRASENA()); txtayudacontrasena.setEditable(true);
            combotienda.setSelectedIndex(0); combotienda.setEnabled(true);
            combopermiso.setSelectedIndex(0); combopermiso.setEnabled(true);
        }
    }//GEN-LAST:event_combotecnicoItemStateChanged

    private void combotiendaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combotiendaItemStateChanged
        if(combotienda.getSelectedIndex()==0){
            this.lbltienda.setText("Tienda Actual(Invalida)");
            this.lbltienda.setForeground(Color.red);
        }
        else{
            this.lbltienda.setForeground(Color.BLACK);
            this.lbltienda.setText("Tienda Actual(" + Tienda.getNOMBRE()+ ")");
            Personal.setMCODTIENDA(((Tienda)combotienda.getSelectedItem()).getCODTIENDA());
        }
    }//GEN-LAST:event_combotiendaItemStateChanged

    private void checkcontrasenaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkcontrasenaItemStateChanged
        if(evt.getStateChange()==1){txtcontrasena.setEchoChar('\0');}
        else{txtcontrasena.setEchoChar('*');}
    }//GEN-LAST:event_checkcontrasenaItemStateChanged

    public void modificar(){
        if(combopermiso.getSelectedIndex()==1){Personal.setMPERMISO("T");}
        if(combopermiso.getSelectedIndex()==2){Personal.setMPERMISO("A");}
        Personal.setMAYUDACONTRASENA(this.txtayudacontrasena.getText());
        Personal.setMCONTRASENA(String.valueOf(this.txtcontrasena.getPassword()));
        Personal.setMNOMBRE_P(this.txtnombre.getText());
        if(OPAlter.esNumerico(this.txttelefono.getText())){
        Personal.setMTELEFONO(Integer.parseInt(this.txttelefono.getText()));
        lbltelefono.setForeground(Color.BLACK);
        }else{
        Personal.setMTELEFONO(null); lbltelefono.setForeground(Color.red);
        }
        if(Personal.modificarPersonalAT()){
        JOptionPane.showMessageDialog(null, "[PERSONAL] MODIFICADO CORRECTAMENTE");
        limpiar();
        }
    }
    public final void limpiar(){
        Personal = new Personal();
        Tienda = new Tienda();
        combotienda.setModel(Tienda.comboTiendas());
        if("00000000-0".equals(Personal.getRUT_P())){combotecnico.setModel(Personal.comboPersonalROOT(23));}
        else{combotecnico.setModel(Personal.comboTecnicosMiTienda(23));}
        txtnombre.setText(""); txtnombre.setEditable(false);
        txttelefono.setText(""); txttelefono.setEditable(false);
        txtcontrasena.setText(""); txtcontrasena.setEditable(false);
        txtayudacontrasena.setText(""); txtayudacontrasena.setEditable(false);
        combotienda.setSelectedIndex(0); combotienda.setEnabled(false);
        combopermiso.setSelectedIndex(0); combopermiso.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkcontrasena;
    private javax.swing.JComboBox combopermiso;
    private javax.swing.JComboBox combotecnico;
    private javax.swing.JComboBox combotienda;
    private javax.swing.JLabel lblayudacontrasena;
    private javax.swing.JLabel lblcombotecnico;
    private javax.swing.JLabel lblcontrasena;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblpermiso;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JLabel lbltienda;
    private javax.swing.JTextField txtayudacontrasena;
    private javax.swing.JPasswordField txtcontrasena;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
