/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Ireport;
import Modelo.OPAlter;
import Modelo.OrdenDeTrabajo;
import Modelo.Personal;
import Modelo.Tienda;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class panelinformerepuestos extends javax.swing.JPanel {
private OrdenDeTrabajo Ordendetrabajo = new OrdenDeTrabajo();
private Tienda Tienda = new Tienda();
private Ireport Ireport = new Ireport();
private DefaultTableModel modelo;
private SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form panelinformerepuestos
     */
    public panelinformerepuestos() {
        initComponents();
        modelo=(DefaultTableModel) tablaordenes.getModel();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        paneltiendas = new javax.swing.JPanel();
        lbltiendas = new javax.swing.JLabel();
        combotiendas = new javax.swing.JComboBox();
        checktiendas = new javax.swing.JCheckBox();
        panelordenes = new javax.swing.JPanel();
        scrolltablaordenes = new javax.swing.JScrollPane();
        tablaordenes = new javax.swing.JTable();
        lblrepuestos = new javax.swing.JLabel();
        txtcodorden = new javax.swing.JTextField();
        panelestado = new javax.swing.JPanel();
        lblestados = new javax.swing.JLabel();
        checkingresado = new javax.swing.JCheckBox();
        checkprocesando = new javax.swing.JCheckBox();
        checkterminado = new javax.swing.JCheckBox();
        checkentregado = new javax.swing.JCheckBox();
        panelfechas = new javax.swing.JPanel();
        radioestemes1 = new javax.swing.JRadioButton();
        radioesteaño1 = new javax.swing.JRadioButton();
        radioentre1 = new javax.swing.JRadioButton();
        lbla = new javax.swing.JLabel();
        spinnerfechaini1 = new javax.swing.JSpinner();
        spinnerfechafin1 = new javax.swing.JSpinner();
        separadorfechas = new javax.swing.JSeparator();
        spinnerfechafin2 = new javax.swing.JSpinner();
        lbla1 = new javax.swing.JLabel();
        spinnerfechaini2 = new javax.swing.JSpinner();
        radioentre2 = new javax.swing.JRadioButton();
        radioesteaño2 = new javax.swing.JRadioButton();
        radioestemes2 = new javax.swing.JRadioButton();
        radiofechaingreso = new javax.swing.JRadioButton();
        radiofechaentrega = new javax.swing.JRadioButton();
        radiohoy1 = new javax.swing.JRadioButton();
        radiohoy2 = new javax.swing.JRadioButton();
        panelestadosrepuestos = new javax.swing.JPanel();
        lblestadosrepuestos = new javax.swing.JLabel();
        checkdisponible = new javax.swing.JCheckBox();
        checknodisponible = new javax.swing.JCheckBox();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        paneltiendas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbltiendas.setText("Seleccione Tienda Para generar Informe");

        checktiendas.setText("Considerar Todas las Tiendas");
        checktiendas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checktiendasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout paneltiendasLayout = new javax.swing.GroupLayout(paneltiendas);
        paneltiendas.setLayout(paneltiendasLayout);
        paneltiendasLayout.setHorizontalGroup(
            paneltiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltiendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneltiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltiendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combotiendas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checktiendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneltiendasLayout.setVerticalGroup(
            paneltiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltiendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltiendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combotiendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checktiendas)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panelordenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaordenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Orden", "Num Orden", "Repuesto", "Estado Repuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaordenes.getTableHeader().setReorderingAllowed(false);
        scrolltablaordenes.setViewportView(tablaordenes);
        tablaordenes.getColumnModel().getColumn(1).setMinWidth(0);
        tablaordenes.getColumnModel().getColumn(1).setPreferredWidth(0);
        tablaordenes.getColumnModel().getColumn(1).setMaxWidth(0);

        lblrepuestos.setText("<html><body>Ingrese los Codigos de Ordenes para <br> Actualizar sus Repuestos<body><html>");

        txtcodorden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodordenKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelordenesLayout = new javax.swing.GroupLayout(panelordenes);
        panelordenes.setLayout(panelordenesLayout);
        panelordenesLayout.setHorizontalGroup(
            panelordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelordenesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelordenesLayout.createSequentialGroup()
                        .addComponent(lblrepuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                        .addGap(66, 66, 66))
                    .addGroup(panelordenesLayout.createSequentialGroup()
                        .addGroup(panelordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcodorden)
                            .addComponent(scrolltablaordenes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelordenesLayout.setVerticalGroup(
            panelordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelordenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblrepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcodorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrolltablaordenes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelestado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblestados.setText("Selecciones el estado de las ordenes a Considerar");

        checkingresado.setSelected(true);
        checkingresado.setText("Ingresado");

        checkprocesando.setSelected(true);
        checkprocesando.setText("Procesando");

        checkterminado.setText("Terminado");

        checkentregado.setText("Entregado");

        javax.swing.GroupLayout panelestadoLayout = new javax.swing.GroupLayout(panelestado);
        panelestado.setLayout(panelestadoLayout);
        panelestadoLayout.setHorizontalGroup(
            panelestadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelestadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelestadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblestados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkingresado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkprocesando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkterminado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkentregado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelestadoLayout.setVerticalGroup(
            panelestadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelestadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblestados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkingresado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkprocesando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkterminado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkentregado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelfechas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup2.add(radioestemes1);
        radioestemes1.setSelected(true);
        radioestemes1.setText("Este Mes");

        buttonGroup2.add(radioesteaño1);
        radioesteaño1.setText("Este Año");

        buttonGroup2.add(radioentre1);
        radioentre1.setText("Entre");
        radioentre1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioentre1ItemStateChanged(evt);
            }
        });

        lbla.setText("A");

        spinnerfechaini1.setModel(new javax.swing.SpinnerDateModel());
        spinnerfechaini1.setEnabled(false);

        spinnerfechafin1.setModel(new javax.swing.SpinnerDateModel());
        spinnerfechafin1.setEnabled(false);

        separadorfechas.setOrientation(javax.swing.SwingConstants.VERTICAL);

        spinnerfechafin2.setModel(new javax.swing.SpinnerDateModel());
        spinnerfechafin2.setEnabled(false);

        lbla1.setText("A");

        spinnerfechaini2.setModel(new javax.swing.SpinnerDateModel());
        spinnerfechaini2.setEnabled(false);

        buttonGroup3.add(radioentre2);
        radioentre2.setText("Entre");
        radioentre2.setEnabled(false);
        radioentre2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioentre2ItemStateChanged(evt);
            }
        });

        buttonGroup3.add(radioesteaño2);
        radioesteaño2.setText("Este Año");
        radioesteaño2.setEnabled(false);

        buttonGroup3.add(radioestemes2);
        radioestemes2.setSelected(true);
        radioestemes2.setText("Este Mes");
        radioestemes2.setEnabled(false);

        buttonGroup1.add(radiofechaingreso);
        radiofechaingreso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radiofechaingreso.setSelected(true);
        radiofechaingreso.setText("Filtro por fecha de Ingreso");
        radiofechaingreso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radiofechaingresoItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radiofechaentrega);
        radiofechaentrega.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radiofechaentrega.setText("Filtro por fecha de Entrega");
        radiofechaentrega.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radiofechaentregaItemStateChanged(evt);
            }
        });

        buttonGroup2.add(radiohoy1);
        radiohoy1.setText("Hoy");

        buttonGroup3.add(radiohoy2);
        radiohoy2.setText("Hoy");
        radiohoy2.setEnabled(false);

        javax.swing.GroupLayout panelfechasLayout = new javax.swing.GroupLayout(panelfechas);
        panelfechas.setLayout(panelfechasLayout);
        panelfechasLayout.setHorizontalGroup(
            panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radiofechaingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelfechasLayout.createSequentialGroup()
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radioestemes1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioesteaño1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelfechasLayout.createSequentialGroup()
                                .addComponent(radioentre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerfechaini1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radiohoy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerfechafin1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71)
                .addComponent(separadorfechas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radiofechaentrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelfechasLayout.createSequentialGroup()
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(radioestemes2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioesteaño2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelfechasLayout.createSequentialGroup()
                                .addComponent(radioentre2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerfechaini2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelfechasLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lbla1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerfechafin2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(panelfechasLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(radiohoy2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        panelfechasLayout.setVerticalGroup(
            panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorfechas)
                    .addGroup(panelfechasLayout.createSequentialGroup()
                        .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelfechasLayout.createSequentialGroup()
                                .addComponent(radiofechaingreso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioestemes1)
                                    .addComponent(radiohoy1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioesteaño1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioentre1)
                                    .addComponent(lbla)
                                    .addComponent(spinnerfechaini1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerfechafin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelfechasLayout.createSequentialGroup()
                                .addComponent(radiofechaentrega)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioestemes2)
                                    .addComponent(radiohoy2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioesteaño2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelfechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioentre2)
                                    .addComponent(lbla1)
                                    .addComponent(spinnerfechaini2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerfechafin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelestadosrepuestos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblestadosrepuestos.setText("Estados repuestos a considerar en el informe:");

        checkdisponible.setSelected(true);
        checkdisponible.setText("Disponibles");

        checknodisponible.setSelected(true);
        checknodisponible.setText("No Disponibles");

        javax.swing.GroupLayout panelestadosrepuestosLayout = new javax.swing.GroupLayout(panelestadosrepuestos);
        panelestadosrepuestos.setLayout(panelestadosrepuestosLayout);
        panelestadosrepuestosLayout.setHorizontalGroup(
            panelestadosrepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelestadosrepuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelestadosrepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblestadosrepuestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelestadosrepuestosLayout.createSequentialGroup()
                        .addComponent(checkdisponible)
                        .addGap(48, 48, 48)
                        .addComponent(checknodisponible)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelestadosrepuestosLayout.setVerticalGroup(
            panelestadosrepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelestadosrepuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblestadosrepuestos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelestadosrepuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkdisponible)
                    .addComponent(checknodisponible))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelfechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelestadosrepuestos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paneltiendas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelestado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelordenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneltiendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelestadosrepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelordenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelfechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodordenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodordenKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_TAB || evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtcodorden.requestFocus();
            try{
                Ordendetrabajo.setNUM_ORDEN(Integer.parseInt(txtcodorden.getText().substring(6, txtcodorden.getText().length())));
                Ordendetrabajo.setIMEI(txtcodorden.getText().substring(0, 3));
                if(Ordendetrabajo.buscarOrden()&&Ordendetrabajo.buscadatoentabla(modelo,Ordendetrabajo.getNUM_ORDEN())){
                    modelo=Ordendetrabajo.tablaRepuestos2(modelo, Ordendetrabajo.getNUM_ORDEN());
                }else{}
            }
            catch(Exception e){}
        }
    }//GEN-LAST:event_txtcodordenKeyPressed

    private void radioentre1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioentre1ItemStateChanged
        if(evt.getStateChange()==1){
            spinnerfechaini1.setEnabled(true);
            spinnerfechafin1.setEnabled(true);
        }else{
            spinnerfechaini1.setEnabled(false);
            spinnerfechafin1.setEnabled(false);
        }
    }//GEN-LAST:event_radioentre1ItemStateChanged

    private void radioentre2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioentre2ItemStateChanged
        if(evt.getStateChange()==1){
            spinnerfechaini2.setEnabled(true);
            spinnerfechafin2.setEnabled(true);
        }else{
            spinnerfechaini2.setEnabled(false);
            spinnerfechafin2.setEnabled(false);
        }
    }//GEN-LAST:event_radioentre2ItemStateChanged

    private void radiofechaingresoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radiofechaingresoItemStateChanged
        if(evt.getStateChange()==1){
            radioestemes1.setEnabled(true);
            radioesteaño1.setEnabled(true);
            radioentre1.setEnabled(true);
            radiohoy1.setEnabled(true);
            spinnerfechaini2.setEnabled(false);
            spinnerfechafin2.setEnabled(false);
            radioestemes2.setEnabled(false);
            radioesteaño2.setEnabled(false);
            radioentre2.setEnabled(false);
            radiohoy2.setEnabled(false);
            if(radioentre1.isSelected()){
                spinnerfechaini1.setEnabled(true);
                spinnerfechafin1.setEnabled(true);
            }
        }
    }//GEN-LAST:event_radiofechaingresoItemStateChanged

    private void radiofechaentregaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radiofechaentregaItemStateChanged
        if(evt.getStateChange()==1){
            radioestemes2.setEnabled(true);
            radioesteaño2.setEnabled(true);
            radioentre2.setEnabled(true);
            radiohoy2.setEnabled(true);
            spinnerfechaini1.setEnabled(false);
            spinnerfechafin1.setEnabled(false);
            radioestemes1.setEnabled(false);
            radioesteaño1.setEnabled(false);
            radioentre1.setEnabled(false);
            radiohoy1.setEnabled(false);
            if(radioentre2.isSelected()){
                spinnerfechaini2.setEnabled(true);
                spinnerfechafin2.setEnabled(true);
            }
        }
    }//GEN-LAST:event_radiofechaentregaItemStateChanged

    private void checktiendasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checktiendasItemStateChanged
        if(evt.getStateChange()==1){this.combotiendas.setEnabled(false);}
        else{combotiendas.setEnabled(true);}
    }//GEN-LAST:event_checktiendasItemStateChanged

    public void mostrarInforme(){
        String ESTADO1 = "", ESTADO2 = "", ESTADO3 = "", ESTADO4 = "";
        String FECHAINI1 = "", FECHAFIN1 = "", FECHAINI2 = "", FECHAFIN2 = "";
        String COD_TIENDA = "";
        Integer MI_COD_TIENDA = Personal.getCODTIENDA();
        String FECHA = "";
        boolean DISPONIBLE1=true, DISPONIBLE2=false;
        if(checkingresado.isSelected()){ESTADO1=checkingresado.getText();}
        if(checkprocesando.isSelected()){ESTADO2=checkprocesando.getText();}
        if(checkterminado.isSelected()){ESTADO3=checkterminado.getText();}
        if(checkentregado.isSelected()){ESTADO4=checkentregado.getText();}
        if(radiofechaingreso.isSelected()){
            FECHA="FECHA DE INGRESO";
            FECHAFIN1=df.format(new Date());
            if(radioestemes1.isSelected()){
                FECHAINI1=df.format(OPAlter.restamesano(new Date(), "mes", -1));
            }
            if(radioesteaño1.isSelected()){
                FECHAINI1=df.format(OPAlter.restamesano(new Date(), "año", -1));
            }
            if(radiohoy1.isSelected()){
                FECHAINI1=df.format(OPAlter.restamesano(new Date(), "dia", 0));
            }
            if(radioentre1.isSelected()){
                    FECHAINI1=df.format(spinnerfechaini1.getModel().getValue());
                    FECHAFIN1=df.format(spinnerfechafin1.getModel().getValue());
            }
        }
        if(radiofechaentrega.isSelected()){
            FECHA="FECHA DE ENTREGA";
            FECHAFIN2=df.format(new Date());
            if(radioestemes2.isSelected()){
                FECHAINI2=df.format(OPAlter.restamesano(new Date(), "mes", -1));
            }
            if(radioesteaño2.isSelected()){
                FECHAINI2=df.format(OPAlter.restamesano(new Date(), "año", -1));
            }
            if(radiohoy2.isSelected()){
                FECHAINI2=df.format(OPAlter.restamesano(new Date(), "dia", 0));
            }
            if(radioentre2.isSelected()){
                    FECHAINI2=df.format(spinnerfechaini2.getModel().getValue());
                    FECHAFIN2=df.format(spinnerfechafin2.getModel().getValue());                
            }
        }
        if(checktiendas.isSelected()){
            COD_TIENDA="";
        }else{
            if(combotiendas.getSelectedIndex()!=0){
                COD_TIENDA=String.valueOf(((Tienda)combotiendas.getSelectedItem()).getCODTIENDA());
            }else{
                COD_TIENDA="COD_TIENDA";
            }
        }
        if(checkdisponible.isSelected() && checknodisponible.isSelected()){DISPONIBLE1=true;DISPONIBLE2=false;}
        else{
            if(checkdisponible.isSelected()){DISPONIBLE1=true;DISPONIBLE2=true;}
            if(checknodisponible.isSelected()){DISPONIBLE1=false;DISPONIBLE2=false;}
        }
        Ireport.peticionRepuestos(ESTADO1, ESTADO2, ESTADO3, ESTADO4, FECHAINI1, FECHAFIN1, FECHAINI2, FECHAFIN2, FECHA, MI_COD_TIENDA, COD_TIENDA, DISPONIBLE1, DISPONIBLE2).setVisible(true);
    }
    
    public void actualizarestado(){
        for(int i=0;i<modelo.getRowCount();i++){
            Ordendetrabajo.EliminaRepuesto((Integer)modelo.getValueAt(i, 1));
        }
        Ordendetrabajo.IngresaRepuesto(modelo);
    }
    
    public final void limpiar(){
        JSpinner.DateEditor editor1= new JSpinner.DateEditor(spinnerfechaini1, "dd/MM/yyyy");
        JFormattedTextField ftf1 = editor1.getTextField();
        ftf1.setEditable(false);
        spinnerfechaini1.setEditor(editor1);
        JSpinner.DateEditor editor2= new JSpinner.DateEditor(spinnerfechafin1, "dd/MM/yyyy");
        JFormattedTextField ftf2 = editor2.getTextField();
        ftf2.setEditable(false);
        spinnerfechafin1.setEditor(editor2);
        JSpinner.DateEditor editor3= new JSpinner.DateEditor(spinnerfechaini2, "dd/MM/yyyy");
        JFormattedTextField ftf3 = editor3.getTextField();
        ftf3.setEditable(false);
        spinnerfechaini2.setEditor(editor3);
        JSpinner.DateEditor editor4= new JSpinner.DateEditor(spinnerfechafin2, "dd/MM/yyyy");
        JFormattedTextField ftf4 = editor4.getTextField();
        ftf4.setEditable(false);
        spinnerfechafin2.setEditor(editor4);
        txtcodorden.setText("");
        modelo.setRowCount(0);
        combotiendas.setModel(Tienda.comboTiendas());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox checkdisponible;
    private javax.swing.JCheckBox checkentregado;
    private javax.swing.JCheckBox checkingresado;
    private javax.swing.JCheckBox checknodisponible;
    private javax.swing.JCheckBox checkprocesando;
    private javax.swing.JCheckBox checkterminado;
    private javax.swing.JCheckBox checktiendas;
    private javax.swing.JComboBox combotiendas;
    private javax.swing.JLabel lbla;
    private javax.swing.JLabel lbla1;
    private javax.swing.JLabel lblestados;
    private javax.swing.JLabel lblestadosrepuestos;
    private javax.swing.JLabel lblrepuestos;
    private javax.swing.JLabel lbltiendas;
    private javax.swing.JPanel panelestado;
    private javax.swing.JPanel panelestadosrepuestos;
    private javax.swing.JPanel panelfechas;
    private javax.swing.JPanel panelordenes;
    private javax.swing.JPanel paneltiendas;
    private javax.swing.JRadioButton radioentre1;
    private javax.swing.JRadioButton radioentre2;
    private javax.swing.JRadioButton radioesteaño1;
    private javax.swing.JRadioButton radioesteaño2;
    private javax.swing.JRadioButton radioestemes1;
    private javax.swing.JRadioButton radioestemes2;
    private javax.swing.JRadioButton radiofechaentrega;
    private javax.swing.JRadioButton radiofechaingreso;
    private javax.swing.JRadioButton radiohoy1;
    private javax.swing.JRadioButton radiohoy2;
    private javax.swing.JScrollPane scrolltablaordenes;
    private javax.swing.JSeparator separadorfechas;
    private javax.swing.JSpinner spinnerfechafin1;
    private javax.swing.JSpinner spinnerfechafin2;
    private javax.swing.JSpinner spinnerfechaini1;
    private javax.swing.JSpinner spinnerfechaini2;
    private javax.swing.JTable tablaordenes;
    private javax.swing.JTextField txtcodorden;
    // End of variables declaration//GEN-END:variables
}
