/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Equipo;
import Modelo.OPAlter;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class panelmodificarequipo extends javax.swing.JPanel {
private OPAlter OPAlter;
private Equipo Equipo = new Equipo();
    /**
     * Creates new form panelmodificarequipo
     */
    public panelmodificarequipo() {
        initComponents();
        txtfabricante.setDocument(new RestringeTextField(50));
        txtimei.setDocument(new RestringeTextField(60));
        txtmodelo.setDocument(new RestringeTextField(0,true));
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmodelo = new javax.swing.JLabel();
        txtfabricante = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        lblimei = new javax.swing.JLabel();
        lblfabricante = new javax.swing.JLabel();
        txtimei = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        lblmodelo.setText("Modelo");

        txtfabricante.setEditable(false);
        txtfabricante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfabricanteFocusLost(evt);
            }
        });
        txtfabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfabricanteKeyReleased(evt);
            }
        });

        txtmodelo.setEditable(false);
        txtmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmodeloKeyReleased(evt);
            }
        });

        lblimei.setText("Imei (TAC)");

        lblfabricante.setText("Fabricante");

        txtimei.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtimeiFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblimei, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(txtimei)
                    .addComponent(lblfabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfabricante)
                    .addComponent(lblmodelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtmodelo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblimei, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtimei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblfabricante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblmodelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfabricanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfabricanteFocusLost
        Equipo.setMARCA(txtfabricante.getText());
    }//GEN-LAST:event_txtfabricanteFocusLost

    private void txtfabricanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfabricanteKeyReleased
        if(txtfabricante.isEditable()){
            switch(evt.getKeyCode()){
                case KeyEvent.VK_BACK_SPACE:
                break;
                case KeyEvent.VK_DELETE:
                break;
                default:
                Equipo.setMARCA(txtfabricante.getText().substring(0, txtfabricante.getSelectionStart()));
                txtfabricante.setText(Equipo.getMARCA()+Equipo.buscarMarca());
                txtfabricante.select(Equipo.getMARCA().length(), txtfabricante.getText().length());
                break;
            }
        }
    }//GEN-LAST:event_txtfabricanteKeyReleased

    private void txtmodeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmodeloKeyReleased
        if(txtmodelo.isEditable()){
            switch(evt.getKeyCode()){
                case KeyEvent.VK_BACK_SPACE:
                break;
                case KeyEvent.VK_DELETE:
                break;
                default:
                Equipo.setMODELO(txtmodelo.getText().substring(0, txtmodelo.getSelectionStart()));
                txtmodelo.setText(Equipo.getMODELO()+Equipo.buscarModelo());
                txtmodelo.select(Equipo.getMODELO().length(), txtmodelo.getText().length());
                break;
            }
        }
    }//GEN-LAST:event_txtmodeloKeyReleased

    private void txtimeiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtimeiFocusLost
        if(OPAlter.validaimei(txtimei.getText())){
            Equipo.setIMEI(txtimei.getText().substring(0, 8));
            if(Equipo.buscarImei()){
                lblimei.setText("Imei (TAC) (Existente)");
                lblimei.setForeground(Color.black);
                txtfabricante.setText(Equipo.getMARCA());
                txtmodelo.setText(Equipo.getMODELO());
                txtfabricante.setEditable(true);
                txtmodelo.setEditable(true);
            }
            else{
                Equipo.setIMEI(txtimei.getText().substring(0, 8));
                lblimei.setText("Imei (TAC) (Nuevo)");
                lblimei.setForeground(Color.green.darker().darker());
                txtfabricante.setText("");
                txtmodelo.setText("");
                txtfabricante.setEditable(true);
                txtmodelo.setEditable(true);
            }
        }
        else{
            Equipo.setIMEI(null);
            lblimei.setText("Imei (TAC) (Invalido");
            lblimei.setForeground(Color.red);
            txtfabricante.setText("");
            txtmodelo.setText("");
            txtfabricante.setEditable(false);
            txtmodelo.setEditable(false);
        }
    }//GEN-LAST:event_txtimeiFocusLost

    public void agregarmodificar (){
        Equipo.setMARCA(txtfabricante.getText());
        Equipo.setMODELO(txtmodelo.getText());
        if(Equipo.crearEquipo()){JOptionPane.showMessageDialog(null, "Equipo Creado Correctamente"); limpiar();}
        else if(Equipo.modificarEquipo()){JOptionPane.showMessageDialog(null, "Equipo Modificado Correctamente"); limpiar();}
    }
    
    public final void limpiar(){
        Equipo = new Equipo();
        txtimei.setText("");
        txtfabricante.setText("");
        txtfabricante.setEditable(false);
        txtmodelo.setText("");
        txtmodelo.setEditable(false);
        lblimei.setText("Imei (TAC)");
        lblimei.setForeground(Color.BLACK);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblfabricante;
    private javax.swing.JLabel lblimei;
    private javax.swing.JLabel lblmodelo;
    private javax.swing.JTextField txtfabricante;
    private javax.swing.JTextField txtimei;
    private javax.swing.JTextField txtmodelo;
    // End of variables declaration//GEN-END:variables
}
